### ISSUE TITLE
2345-0008 when I reach extraction

### ISSUE THREAD

**Issue by colinkelly06** [HamletDuFromage/aio-switch-updater#100]
The moment it tries to extract atmosphere crashes with error code 2345-0008(0x1159)

**Comment by HamletDuFromage** [comment]
Are you using a forwarder? If so, you shouldn't

**Comment by colinkelly06** [comment]
I am not

**Comment by HamletDuFromage** [comment]
Welp, that sucks. Are you using title redirection? Either way could you upload your crash report?

**Comment by jacklee-code** [comment]
yep i have the same issue in applet mode and non-applet mode. atmosphere crash when extract cheats code

**Comment by HamletDuFromage** [comment]
Hey @jacklee-code Could you answer those questions please?
Are you using exFAT?
Which ams version/fw are you on?
Does the same crash happen when going in the "download individual cheats from gbatemp" menu
Are you using a forwarder
Do you have a bunch of sysmodules active and if so does it happen with them disabled?

**Comment by jacklee-code** [comment]
> Hey @jacklee-code Could you answer those questions please?
> Are you using exFAT?
> Which ams version/fw are you on?
> Does the same crash happen when going in the "download individual cheats from gbatemp" menu
> Are you using a forwarder
> Do you have a bunch of sysmodules active and if so does it happen with them disabled?
> Is it also error 2345-0008(0x1159)

no i am using fas32
atmosphere 0.19.4  with fw 12.03
havent try yet
yes, iam using NX_Payload_Forwarder
yes i am enable some module like missioncontrol in deepsea tool, i will disable and try it again

Thanks for your reply

**Comment by HamletDuFromage** [comment]
>yes, iam using NX_Payload_Forwarder

No, I meant to ask if you launched the app through title redirection or through a homebrew menu nsp

Thank you for your answer though. But is it also error 2345-0008(0x1159)?

**Comment by jacklee-code** [comment]
I start it in album.
I just removed the original aio updater then download re-install it again. Now the updater work perfectly. Thx a lot, perhaps it is some file problem i guess.
Sorry for my poor English

**Comment by DarkPrinceChrono** [comment]
I'm getting the same after the most recent app update, my error code is 2349-0008 (0x115d) launched through title redirect. Haven't tried through album launch

**Comment by DarkPrinceChrono** [comment]
@HamletDuFromage So, the only thing crashing on me right now is when I try to download the new gbatemp cheat repository, I can download single at a time without crash, nothing else seemed to error out... I'll have to get back to you, on the crash report.

**Comment by HamletDuFromage** [comment]
How many games do you have installed?

**Comment by DarkPrinceChrono** [comment]
I think about 73

**Comment by HamletDuFromage** [comment]
So I've seen reports a few reports of that kind of crash now, but I could never pinpoint it. I would really appreciate the crash logs. Also are you using exFAT by any chance?

**Comment by DarkPrinceChrono** [comment]
Fat32 1tb SanDisk extreme. I'll get to the PC and look for those logs in a moment.

**Comment by DarkPrinceChrono** [comment]
[01627761186_010043b013c5c000.log](https://github.com/HamletDuFromage/aio-switch-updater/files/6935005/01627761186_010043b013c5c000.log)
[01628025912_010070100f782000.log](https://github.com/HamletDuFromage/aio-switch-updater/files/6935012/01628025912_010070100f782000.log)
different dates and stuff.. The only thing I can think of is recently I upgraded through the program, I downloaded 12.1.0 and updated... Idk if that would cause it or not, cause nothing else has been having issues, I don't remember exactly when I updated either, though.
Hopefully these help

**Comment by HamletDuFromage** [comment]
Could you all try again with the latest version?

**Comment by colinkelly06** [comment]
btw it turned out to be a sucky internet connection
