### ISSUE TITLE
2144-0001 for AIO Switch Updater and JC Color Swapper

### ISSUE THREAD

**Issue by TokyoHam** [HamletDuFromage/aio-switch-updater#102]
I'm unable to open either of these apps on 12.0.3 (Atmosphere 0.19.4) whereas my other home-brew are working fine (Goldleaf, Awoo, JKSV, etc) ... I've updated sigpatches etc, but just these two app refuse to open. Any suggestions?

**Comment by HamletDuFromage** [comment]
So assuming you have the latest versions installed, what you wanna do is first clean install atmosphere again (you might be missing some hbl related files), and if that doesn't work, check for corruption on your sd card. I'm on the same fw and cfw and it works for me

**Comment by TokyoHam** [comment]
Thanks for the reply! I'll give that a shot later today and will edit this post after. Thanks again!

**Comment by HamletDuFromage** [comment]
Closing because it has been a while, feel free to reopen if your issue persists
