### ISSUE TITLE
Wiped my /switch folder and all my homebrew, crashed when downloading firmware

### ISSUE THREAD

**Issue by dontdeadopeninside** [HamletDuFromage/aio-switch-updater#103]
Updated Atmosphere, sigpatches, hekate just fine. When it finished downloading the firmware, it had the Atmosphere crash screen, restarted and loaded up hbloader to find that it claimed there was nothing in /switch. Sure enough on the PC there is nothing there.

**Comment by HamletDuFromage** [comment]
Uh that's a new one, and most definitely odd. That looks like corruption, you should check your sd card for it before continuing to use it. Are you using exFAT?

**Comment by dontdeadopeninside** [comment]
Yea exFAT. I understand the dangers of corruption, but I sadly can't stop using it for reasons. I couldn't recover the files from the SD Card, but Windows did find and fix corruption. I had a backup so its not that huge of a problem to me at least.

**Comment by HamletDuFromage** [comment]
Ah ok, thanks for letting me know. I'm glad you didn't lose anything of value.
I'll change the text on the warning screen to say you really shouldn't use exFAT
