### ISSUE TITLE
option 'View installed cheats' is gone from v2.7.0 with no mention in the changelog

### ISSUE THREAD

**Issue by ms2048** [HamletDuFromage/aio-switch-updater#105]
I've just updated from v2.6.0 to v2.7.0 and the option to display a list of games with cheats downloaded (Tools -> Cheats menu -> View installed cheats) is gone and nowhere to be found. For now, I had to downgrade because of this...

It is crucial (at least to me) when browsing the cheats on the switch itself, especially in case of different updates to games, so that for example in Edizon they are gone, despite still being there. The only alternative is diving into the non-intuitively-named directories, which is tedious and needlessly time consuming.

Could you please bring this option back? Thank you!

**Comment by HamletDuFromage** [comment]
Yeah, I removed because it could cause crashes in applet mode and wasn't very well integrated with the download individual cheats option. Also I figured no one used it. I'll bring it back for you though

**Comment by ms2048** [comment]
Thank you, I really appreciate this!

If you know of any better method of browsing through installed cheats and - even better - through different build IDs, I'd gladly use it but for now - AIO-switch-updater it is :). As simplistic as it may seem, I know which games have any cheats at a glance, and without leaving switch or memorizing IDs.

**Comment by HamletDuFromage** [comment]
I'll keep in mind the build ID request, but next version that I will release shortly will at least restore the old menu back, and it will be more reliable too

**Comment by ms2048** [comment]
That's great - if you're going to expand on this then I'd also suggest to allow for viewing cheat files itself from within this menu, even as a simple text preview.

**Comment by HamletDuFromage** [comment]
https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.8.0

**Comment by ms2048** [comment]
I've just tested 2.8.0 and this is a huge improvement for me, thank you for this!
