### ISSUE TITLE
AIO switch updater cheats weren't appearing in game, and now it wont launch at all.

### ISSUE THREAD

**Issue by HenryHeliolisk** [HamletDuFromage/aio-switch-updater#106]
**Describe the bug**
Before, when I downloaded cheats for a new game, the cheats wouldn't appear even after I vchecked their placment and IDs. And now the app wont even start, instead crashing the system with the same error code.

**To Reproduce**
On a switch with amosphere 0.19.4, download AIO switch updater through any source, open the updater, and watch the switch crash

**Screenshots/Crash code/Crash reports**
https://github.com/Atmosphere-NX/Atmosphere/files/6722457/01624834306_010000000000100d.log

**System Firmware Version and CFW Version**
 - System Firmware: 12.0.3
 - CFW Version  0.19.4

The old cheats i have for older games still work, and its only after updating atmosphere that this occurred.

**Comment by HamletDuFromage** [comment]
Do you still have this issue?
