### ISSUE TITLE
suggestion: better offline behavior

### ISSUE THREAD

**Issue by ms2048** [HamletDuFromage/aio-switch-updater#107]
Right now, when I tried adding cheats from gbatemp in v2.6.0 while being offline, the program didn't even show an option to do so, despite having (as far as I understand) all the cheats cached in /config/aio-switch-updater/cheats.zip.

In case there is some download failure (like when offline), maybe just allow the use of the cached version as if it has been freshly downloaded? This would be useful when some games are added. Additionally, it will indirectly 'kind of' future-proof the most useful function of this software (like allow for providing some custom zip... well, maybe I'm overthinking this, but I hope it is clear what I mean).

Also, I noticed that even when the version (number) online is the same as the one already cached, the program still redownloads the whole file, which is wasteful (not critical tbh, as the file is small).

**Comment by HamletDuFromage** [comment]
>despite having (as far as I understand) all the cheats cached in /config/aio-switch-updater/cheats.zip.

Not quite, it pulls from there https://github.com/HamletDuFromage/switch-cheats-db/tree/master/cheats which the gbatemp cheats but automatically processed

>In case there is some download failure (like when offline), maybe just allow the use of the cached version as if it has been freshly downloaded?

As to caching the file, that could be done but that's not going a top priority for now. I'll leave the issue open though

**Comment by ms2048** [comment]
I don't really know why you've closed this issue, as the behavior when offline is exactly the same as described (still in v2.16.1), i.e. when offline, the option to extract cheats isn't there at all, only the redownloading (when online) got solved

**Comment by ms2048** [comment]
Confirmed working. The term 'download' used when offline might be somewhat confusing for new users. Otherwise everything seems perfect, thank you!
