### ISSUE TITLE
Payload doesn't run on Mariko switches that use a modified name for payload.bin

### ISSUE THREAD

**Issue by Ericvf** [HamletDuFromage/aio-switch-updater#110]
**Describe the bug**
The title says it all. I'm using a Switch V2 Mariko and updated Hekate first. 

**To Reproduce**
Be on `12.0.3|AMS M.19.4|E`
Update Hekate from `5.5.7` to `5.5.8` using AIO
Update Atmosphere to `0.19.5` using AIO
Reboot
The system version of Atmosphere still said `12.0.3|AMS M.19.4|E`. 

**System Firmware Version and CFW Version**
 - System Firmware: 12.0.3
 - CFW Version . Atmospshère 0.19.4

**SD card format**
FAT32 

**Additional context**
I did notice that some files were updated. For example, the `reboot_to_payload.nro` app does not work on Mariko. _I had deleted it and it was added again_. 

On the root of the SDcard was a `payload.bin.aio` which I hadn't put there. I still have a backup of the SD with this situation. 

So I don't know but maybe some finalizing step needs to happen to replace Atmosphere files? Could it be that this relies on rebooting into a AIO payload and that it didn't work for my setup? I'm using SXGear and redirecting to hekate.bin.

To fix it I updated Atmosphere manually and that of course worked!

**Comment by HamletDuFromage** [comment]
Hello!
Yeah you're right, the last step (running the payload) didn't happen, it should have renamed files like `[filename].aio` to `[filename]`. 

I'm a little bit confused though, you're saying your switch is Mariko but isn't the SXGear a payload injector? Also what do you mean by redirecting to hekate.bin, shouldn't your modchip be looking for payload.bin?

**Comment by Ericvf** [comment]
Allright. Thanks for the clarification. I'm probably going to update my setup to make a little more sense. 

As for the Mariko / SXGear:

You can also use the SXGear.dat on Mariko to boot to a custom payload. I'm not using the SXOS bootloader. Just the SXGear.dat with a boot.ini file that points to hekate.bin. This allows me to keep the SXCore (modchip) original firmware instead of Spacecraft-NX. If I kept SXGear at payload.bin I would not have had this problem, so I am going to do that. 

Might I suggest adding a informational message before rebooting to payload.bin? Something that explains that AIO needs to finalize the installation by executing payload.bin? That way it is clear to the user what needs to happen in case it fails.

**Comment by HamletDuFromage** [comment]
I wasn't aware payloads could be named something that is not payload.bin. I'll try to add a warning or something
