### ISSUE TITLE
[Request] Menu entries visibility via json config files 

### ISSUE THREAD

**Issue by rashevskyv** [HamletDuFromage/aio-switch-updater#113]
AiO has a lot features that I want to disable for my pack (such as deapsea or vanilla atmosphere downloading, changing jopycon colors, etc.). 
It would be very nice if i could hide some menu entries without recompiling updater.

Thank you for your awesome work!

**Comment by HamletDuFromage** [comment]
[hide_tabs.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6856166/hide_tabs.zip)
This should do what you want

**Comment by HamletDuFromage** [comment]
https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.11.3
