### ISSUE TITLE
Language bug after update to 2.11.3

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#114]
**Describe the bug**
Language : zh-TW
After I use this language, the app language change to English with very little chinese

**To Reproduce**
Use 2.11.3 aio-switch-updater

**Screenshots/Crash code/Crash reports**
I may upload screenshots later if you want it 

**System Firmware Version and CFW Version**
Not useful in this problem
 - System Firmware: 12.1.0
 - CFW Version Atmospshère 0.19.5

**SD card format**
Not useful in this problem 
Test on both FAT32 or exFAT

**Additional context**
2.11.2 does not have this problem

**Comment by HamletDuFromage** [comment]
thank you for noticing, there was an extra comma in the json file
