### ISSUE TITLE
Request/Suggestion homebrew updates

### ISSUE THREAD

**Issue by pixeltester** [HamletDuFromage/aio-switch-updater#117]
**What feature are you suggesting?**
This tool handles everything very well so far and it would be great if we could specify our own homebrew updates. If I'm not mistaken that's not possible yet in AIO-switch-updater without workarounds.

**Describe the solution you'd like**
A solution similar to what's already implemented where you can specify a list of homebrew you would like to be updated from github or other sources, including custom output locations and the ability to exclude files so you can set things up exactly as you like.

**Describe alternatives you've considered**
The homebrew app store exists but isn't customizable and relies on extra files, I was looking for a more manual and customizable solution which I believe your app could provide. Thank you

**Comment by HamletDuFromage** [comment]
This is way out of scope, would require me to maintain a bunch of stuff I'm not interested in doing, etc. Just use the hbappstore, or DeepSea's custom builder. You could try requesting new packages for DeepSea's custom builder but short of that, I won't support it.

**Comment by pixeltester** [comment]
> This is way out of scope, would require me to maintain a bunch of stuff I'm not interested in doing, etc. Just use the hbappstore, or DeepSea's custom builder.

Ok I didn't realize it would require heavy maintenance, it seemed like the next natural step to include in your app and I thought it would work well using a similar system to what you have included already. 

Those solutions aren't what I was looking for since i wanted to manually customize it as mentioned. Thanks for considering it anyway.
