### ISSUE TITLE
Sigpatch Update

### ISSUE THREAD

**Issue by Ghostk0** [HamletDuFromage/aio-switch-updater#120]
Hello,

Is it possible to launch the sigpatch update directly from aio-switch-updater? Because I have problems with Atmosphere.
Link for latest : [https://github.com/ITotalJustice/patches/releases/tag/12.1.0-0.19.5-r2](url)

Thank You

**Comment by HamletDuFromage** [comment]
Yeah, you can do that. If you can't see the option, unhide the tab in tools->hide tabs

**Comment by Ghostk0** [comment]
Thanks!! but this option should not be hidden ;) 
Is it possible to display which sigpatch versions are installed?

**Comment by HamletDuFromage** [comment]
If you download it from the hbappstore, it'd hidden by default to comply with their rules. Displaying the sigpatches version could be doable, but wouldn't be reliable and frankly not necessary.

Also no, I won't support piracy.
