### ISSUE TITLE
[Feature Request] Nosigchk enabler

### ISSUE THREAD

**Issue by fennectech** [HamletDuFromage/aio-switch-updater#121]
**What feature are you suggesting?**
Nosigchk enabler. Means we wont have to use notepad to enable nosigchk 

**Describe the solution you'd like**
Just a button that adds or removes nosigchk from the hekate_ipl.i I in the proper place

**Describe alternatives you've considered**
N/A

**Additional context**
I dont think any is needed

**Comment by HamletDuFromage** [comment]
Alright but if you don't have it enabled, you can't boot anyways no? I'm not sure adding that makes much sense, not only it's a one and done deal, the only time you would need that is when your switch can't get into cfw.
Unless I don't understand what it does

**Comment by fennectech** [comment]
You can still boot. But sigpatches dont work.   Its possible to continue on nosigchk error now.

**Comment by HamletDuFromage** [comment]
Ah I see. I don't think I will for now, I guess I would prolly accept a PR adding it to the sigpatches section if elegantly done. Hakte_ipl would need to be parsed, open a pop up page showing each section and offering to toggle nosigchk. Something like that
