### ISSUE TITLE
Atmosphere-with-Hekate

### ISSUE THREAD

**Issue by yyoossk** [HamletDuFromage/aio-switch-updater#122]
this is my original package
https://github.com/yyoossk/Atmosphere-with-Hekate
Would you please add it to the aio-switch-updater if you like?

**Comment by HamletDuFromage** [comment]
I won't add it as it's mostly redundant with simply downloading atmosphere and hekate. If you wish to integrate it to aio-switch-updater yourself, you may use this file https://github.com/HamletDuFromage/aio-switch-updater/blob/master/customPacks.json and put it in config/aio-switch-updater
