### ISSUE TITLE
Very slow extract for large pack

### ISSUE THREAD

**Issue by lowburger** [HamletDuFromage/aio-switch-updater#123]
**Describe the bug**
Hi, I make my own package 200MB unzipped with atmosphere and many files homebrew and tools. Extract time almost 20 minutes! I test on NX-shell tool extracting and it takes 2 minutes extract, is it normal?

**To Reproduce**
Only a large pack with thousands of file and 200MB before zip.

**Screenshots/Crash code/Crash reports**
Nothing.

**System Firmware Version and CFW Version**
 - System Firmware: [12.1.0]
 - CFW Version [Atmospshère 0.19.5]

**SD card format**
FAT32

**Additional context**
Nothing.

**Comment by HamletDuFromage** [comment]
Well, each to-be-extracted is checked for a number of conditions, so the more files the worst it is. I'm using a C++ library for all the extraction process, and I'm sure there is some overhead to that too, but I don't know if I'm willing to look into too much. 
I'll keep this in mind however

**Comment by pixeltester** [comment]
It works great for something small but I made a bigger pack to share with some friends and had the same issue, would be great if you could improve the speeds.

**Comment by FlyingBananaTree** [comment]
@HamletDuFromage Ran into this myself and it does seem needlessly slow if you package a lot of files. Perhaps a solution would be to allow users to whitelist directories to skip your checks?

**Comment by HamletDuFromage** [comment]
fixed in https://github.com/HamletDuFromage/aio-switch-updater/commit/64c13a5626b3645d7f14942d97b1f291a9aae540

**Comment by lowburger** [comment]
> fixed in [64c13a5](https://github.com/HamletDuFromage/aio-switch-updater/commit/64c13a5626b3645d7f14942d97b1f291a9aae540)

Feature ready or needs more develop? I test and works fast but crash on 95% extract all attempts.

**Comment by lowburger** [comment]
This fix the crash, thx
