### ISSUE TITLE
[Improvement] Block home button when downloading and extracting 

### ISSUE THREAD

**Issue by rashevskyv** [HamletDuFromage/aio-switch-updater#125]
If you press HOME button while app is downloading something there will be black screen and crash after few seconds. It woulb be nice if you implement blocking of HOME and canceling download process on B button 

Thanx

**Comment by HamletDuFromage** [comment]
I added a way to cancel downloads but I won't block the home button

**Comment by rashevskyv** [comment]
You can block home while downloading process and unblock if it canceled

ср, 22 сент. 2021 г., 22:07 HamletDuFromage ***@***.***>:
