### ISSUE TITLE
Update Sig Patches gone?

### ISSUE THREAD

**Issue by Ninjistix** [HamletDuFromage/aio-switch-updater#132]
**Describe the bug**
the option to update sig patches is gone

**To Reproduce**
Steps to reproduce the behavior.

**Screenshots/Crash code/Crash reports**
![2021082810412200-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/12572974/131221738-45f174a2-ad21-4fce-824c-a1bb9d67f851.jpg)

**System Firmware Version and CFW Version**
 - System Firmware: 12.0.2
 - CFW Version Atmospshère 0.19.5

**SD card format**

exFAT

**Additional context**

**Comment by HamletDuFromage** [comment]
You got it from the hb appstore with disables it by default. Get it back with tools->hide tabs

**Comment by sawyermade** [comment]
I dont see anything about sigpatches under hide tabs, has this been completely removed now?

**Comment by HamletDuFromage** [comment]
@sawyermade  https://github.com/HamletDuFromage/aio-switch-updater/issues/218
