### ISSUE TITLE
Crash on latest update

### ISSUE THREAD

**Issue by Glitch-Code-Design** [HamletDuFromage/aio-switch-updater#135]
Whenever I'm using title override to exclude games for cheats it crashes.

CFW: 1.0.0 atmosphere pre release
SFW: 12.1.0
SD Card: Fat32

[crash_reports.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/7126164/crash_reports.zip)

**Comment by HamletDuFromage** [comment]
Thanks :)
