### ISSUE TITLE
Backing up joycon colors lead to crash; generated profiles not read.

### ISSUE THREAD

**Issue by JonJaded** [HamletDuFromage/aio-switch-updater#137]
**Describe the bug**
Crash when trying to backup joycon colors; generating a profile 

**To Reproduce**
Attempt to backup joycon colors.

**Screenshots/Crash code/Crash reports**
[crash_reports.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/7132430/crash_reports.zip) Program ID: 0100000000001000

[profiles.txt](https://github.com/HamletDuFromage/aio-switch-updater/files/7132458/profiles.txt) (renamed to txt for compatibility.)

**System Firmware Version and CFW Version**
 - FW 12.1.0
 - Atmosphère 1.0.0 pre-release

**SD card format**
FAT32

**Additional context**
Configurations generated by [JCPicker](https://hamletdufromage.github.io/JC-color-picker/JCpicker.html) seem to be named incorrect? They download as `profiles.json` while the default file in the configs directory is named `jc_profiles.json`. Not sure if this is an error or not- regardless profiles aren't being read.

Also: Atmosphère is spelled incorrectly on the default bug report fill in sheet.

**Comment by HamletDuFromage** [comment]
The problem is that the profiles generation through the website was all broken, it didn't create a proper array of json objects. This in turn gave an invalid json file that my app couldn't write the backup on.

I fixed it and it should be working fine. Let me know and thank you for raising the issue

**Comment by JonJaded** [comment]
Forgot to reply- thanks btw! Really appreciate your contributions to the scene overall. <3
