### ISSUE TITLE
Sys-clk database

### ISSUE THREAD

**Issue by jamjazz** [HamletDuFromage/aio-switch-updater#138]
Hi Hamlet !

What would you think of adding a feature to install/update the entries of config.ini file of the RetroNX sys-clk module.
Just like your current script which allows us to install only the cheats of the installed games.
Entries are posted here: https://discord.gg/yXGgpAef. 

Thank you !

**Comment by HamletDuFromage** [comment]
I'm not willing to manually curate the profiles from their discord, not to mention it's a feature they might want to integrate themselves https://github.com/retronx-team/sys-clk-db

It's probably out of the scope of the app too but I'll keep the suggestion open

**Comment by jamjazz** [comment]
Thank you for your reply :)

**Comment by SiTWulf** [comment]
+1
