### ISSUE TITLE
App crash on cancel firmware download

### ISSUE THREAD

**Issue by Tefery** [HamletDuFromage/aio-switch-updater#140]
**Describe the bug**
When tries to cancel a firmware download, the app freezes until I force closing, finally crash and the Switch system finalize it.

**To Reproduce**
- Start downloading any firmware version.
- Cancel pressing +

**System Firmware Version and CFW Version**
 - System Firmware: 12.0.3 and 12.1.0
 - CFW Version: Atmosphère 1.0.0

**SD card format**
exFAT

**Comment by HamletDuFromage** [comment]
I disabled the + button and made it so B cancels the current action
