### ISSUE TITLE
Bug report on cheats - Help 

### ISSUE THREAD

**Issue by tsukina22** [HamletDuFromage/aio-switch-updater#141]
Hello, i really really need help, i use this AIO homebrew to download cheats for the game Ni no Kuni.

I put and actived the cheat, played a little to test it, saved the game, then later i open the game to play again, without the cheats this time, but the cheat was still there! I even went to Tesla menu to see if it was deactivated and it was (Which is quite funny because before i was used to use the cheats updater homebrew to download and play with the cheats and this never had happened, but i change to AIO because was saying that cheats updater couldn't updated anymore)

I try this guide online to change it with the system_config, the two of them, in config folder, taking off the " e changing the number to 0, then i reboot, go back to my save, the cheats was still there!
![Screenshot_2021-09-25-05-39-01-342_com android chrome](https://user-images.githubusercontent.com/75396328/134765852-f2f76058-db60-42bb-920d-5201c5751a64.jpg)

I try to exclude contents folder, exclude the game, but when i go back, cheat was still there, how can this be possible? But is was not like before, i used the cheat to the max HP and MP for Oliver, but the MP and HP was going down this time when i fight, but the number was still max up to 999 HP and MP, like i was really at that level. 

I just putting on to try and see if worked but i wasn't going to use it all game, and i already have 30h, i can't start all over, please, help.

**Comment by HamletDuFromage** [comment]
I'm sorry, I can't really help with that. You'd have to apply another cheat code with your desired value, instead of 999. You might get some help with that if you ask here https://gbatemp.net/threads/cheat-codes-ams-and-sx-os-add-and-request.520293/

In any case, it's not really a aio-switch-updater issue
