### ISSUE TITLE
[UX] Payload updating process

### ISSUE THREAD

**Issue by NotaInutilis** [HamletDuFromage/aio-switch-updater#143]
Current state:
- updating Atmosphère does not update the fusee payload. [This leads to issues like this one](https://www.reddit.com/r/SwitchPirates/comments/ph5pun/fatal_error_mtc_failed_to_find_timing_tablet/) (I've encountered it personally, it boots with an old fusee.bin, crashes, then seems to switch to Atmosphère's reboot payload and boots normally).
- updating payloads is tucked in the tools menu, which is unintuitive. Moreover, after downloading a payload, the user is thrown back to the home "About" page and has to go through all the menus again to download another payload.

Suggestions:
- add a dialogue box to the Atmosphère updating process, it already asks the user if they want to update the bootloader, it can also ask to update the payload
- change the "Update bootloaders" entry to "Update bootloaders and payloads". We group them because they often work together and the bootloader menu is pretty empty. Plus the payload update option is not hidden away anymore: it is a super useful feature that deserves to be in the main menu.

**Comment by HamletDuFromage** [comment]
Atmosphere doesn't come with fusee.bin, nor did it ever come with fusee-primary.bin. It does come with reboot_payload.bin which is properly replaced when updating. If your configuration is looking for fusee.bin somewhere, it is non standard.

If you decide to update hekate, the hekate payload is copied to `bootloader/update.bin`. And if you want more copy operations, you could use `/config/aio-switch-updater/copy_files.txt` as detailed in the README.

Now, it is true that hekate isn't set to reboot_payload.bin by default, which might be something worth considering.

Also your suggestion to group bootloaders and payloads is sensible, I'll probably end up implementing it

**Comment by NotaInutilis** [comment]
My config is pretty standard (Hekate then fusee.bin), it's just that my understanding of how things actually work is not well... that good. :p I haven't got a lot of experience with code and stuff so all I can do is mildly educated guesses on that kind of boot order thing. Seeing your response makes me think that I wasn't super clear with my description of the issue though.

The thing is, on the UX front, there should be a reminder for the user to update their fusee.bin payload when they update Atmosphère, the very same way that AIO already suggests downloading the latest Hekate when we download the latest Atmosphère. It is a very nice feature: expanding it would help reduce friction even further. That way, there's less chances to encounter a boot error when loading an old fusee.bin to a new Atmosphère build.

**Comment by HamletDuFromage** [comment]
Ah, you're chainloading. Yeah, there really any reason to do that, I would just use regular hekate if I were you. If you really insist on it, use `/config/aio-switch-updater/copy_files.txt`.

**Comment by HamletDuFromage** [comment]
I understand your concerns on UX, but since this a way of doing things few people use, and a convoluted one at that, I think it'd make things more confusing for the majority of people who don't chainload

**Comment by NotaInutilis** [comment]
Oh yeah I think I get it now. Thanks for taking some time to discuss it.

**Comment by HamletDuFromage** [comment]
I've implemented your suggestion regarding payloads being in the bootloader menu. I hope everything is somewhat clear now, if not just re-open the issue
