### ISSUE TITLE
Download Firmware & Download Sigpatches Options Aren't Appearing

### ISSUE THREAD

**Issue by SavXL** [HamletDuFromage/aio-switch-updater#144]
I updated Atmosphere to the latest version, and downgraded my EmuMMC from 13.0.0 to 12.1.0 so more apps support it. I initially downloaded AIO from the HB Store but quickly found out that version's apparently gimped and removed those features due to pirating. I replaced the HB Store version with the one from GitHub directly and didn't seem to work either. There's also apparently a Hidden Tabs option that stores them, but I'm not seeing that either. Entering EmuMMC from Hekate directly or using an RCM Loader doesn't help it either, neither does opening AIO in Applet Mode or using Title Takeover. Not sure whether it's been officially removed, but I don't see any of that in the changelogs. I don't mind searching the internet for the Sigpatches and Firmware, but the convenience was very.. well, convenient.

Not sure how I'd reproduce it since everything worked normally before.

![2021092622190300-0E7DF678130F4F0FA2C88AE72B47AFDF](https://user-images.githubusercontent.com/87171080/134849959-4ec1d45c-b700-48fc-b04a-32a03819f629.jpg)

 - System Firmware: [12.1.0]
 - CFW Version [Atmosphère 1.1.1]

FAT32

**Comment by HamletDuFromage** [comment]
The hb appstore gimped their version further. Delete config/aio-switch-updater/hide-tabs.json to get everything back
