### ISSUE TITLE
Hiding "Hide tabs"

### ISSUE THREAD

**Issue by pixeltester** [HamletDuFromage/aio-switch-updater#146]
Hey. I'm opening this to see if you'd reconsider the recent change to remove the ability to hide "Hide tabs". It's basically a repeat of my old issue: https://github.com/HamletDuFromage/aio-switch-updater/issues/53 and you mentioned it there https://github.com/HamletDuFromage/aio-switch-updater/commit/ee181c011dc2f5446d28ffeafdc25a9830931b28#commitcomment-57202186

I agree that it does not make sense to expose this option in the homebrew's "Hide tabs" menu because anyone could activate it and then that menu is gone, which of course would be a major annoyance. However it was not exposed in that menu up to 2.14.0 and the only way to activate it was to manually change the json.

Why is that desirable? It allows the primary user of the system to protect the config and prevents other casual users of the system changing settings, downloading / installing unwanted cfw files and messing up the installation.

Since it was hidden like that I'm unsure why you deactivated it as it was very useful in the case I described, so I'm asking if you'll reconsider activating it as a hidden option again. Thanks.

**Comment by HamletDuFromage** [comment]
The problem with that, other than the fact that I really don't see what harm you could do with my app to begin with and that I don't consider the dog scenario as plausible, is custom packs. An increasing number of people distribute "packs" with a custom hide_tabs.json, which leaves users perplexed as to why some of the options are hidden. If they hide the hide tabs menu, then they most likely have to use a computer to get it back, which defeats the purpose of the app.

Other apps such as title installers, daybreak, file managers etc can cause considerably more damage and they don't have that kind of safety measure. The worst you could do with my app is changing joy con colors or something

**Comment by pixeltester** [comment]
Your application can install atmosphere and various packs, sigpatches and more itself and I don't want that stuff to be touched. It did happen for me which is why I was interested in this in the first place.

Also are these packs you speak about really bothering to hide it? I follow the scene and I've barely seen any mention of that, I think you replied to one person on gbatemp about it and it wasn't even definitive that hide tabs being missing was the issue.
