### ISSUE TITLE
SX OS crashes when exiting the application

### ISSUE THREAD

**Issue by endersstory** [HamletDuFromage/aio-switch-updater#15]
I am on the 3.0.5 beta and on 10.1.0 the application works fine but when I hit + to exit SX OS crashes. It cannot recover and I have to use jig to CFW again. Is 10.1.0 not supported and I should update firmware to 10.2.0? Can I exit the app any other way?

**Comment by nanshihui** [comment]
same problem

**Comment by HamletDuFromage** [comment]
Sorry, I just saw your issue. I'm not sure actually, it should work but I can't test it since I'm on AMS 10.2.0... I'll try to figure it out. Were you on the last version of the app?

**Comment by endersstory** [comment]
Downloaded the latest 1.2.7, first time using the aio app. So no previous versions or data existed on my switch.

I used to copy the cheat file zip from gbatemp and ftp. This app obviously is so much better. But the crashing is creating just as much hassle.

**Comment by HamletDuFromage** [comment]
I understand. Can you not use the home menu to exit the app as a workaround?

**Comment by endersstory** [comment]
I tried hitting the home button but it would not exit. I usually close my apps that way but hitting home didn’t cause any response. I’ll test it out later today and let you know. But pretty sure that did not work.

Haven’t opened the app since making this post.

**Comment by HamletDuFromage** [comment]
And prior to trying to exit, you could navigate the menu just fine? Are you sure it didn't crash before trying to exit? I just tried with my switch and it works, but with AMS

**Comment by endersstory** [comment]
Sorry for not updating but I was using SX launcher to start this up. So I just close the whole app by hitting the home button and no more crashes. 

Don’t know why I didn’t try that earlier. But going to try it with the updated tinfoil and see how it works in that compared to sx launcher.

Otherwise love the app!
