### ISSUE TITLE
SwitchThemeInjector update option

### ISSUE THREAD

**Issue by vos6434** [HamletDuFromage/aio-switch-updater#160]
**What feature are you suggesting?**
Be able to update SwitchThemeInjector from GitHub releases just like Atmosphere and Hekate.

**Describe the solution you'd like**
Show what version of SwitchThemeInjector you are using and be able to update it.

**Describe alternatives you've considered**
Having to download on pc and transfer to the ad card which defeats the purpose of this homebrew.

**Additional context**

**Comment by HamletDuFromage** [comment]
Out of scope, use the hb app store
