### ISSUE TITLE
Bugs in atmosphere 1.2.2

### ISSUE THREAD

**Issue by bjulio10** [HamletDuFromage/aio-switch-updater#161]
**Description of what the bug is:** 
After atmosphere updated to version 1.2.1 and 1.2.2, I'm having trouble to download, update and manage the cheats. Sometimes, the cheats doesn't update correctly and apears "Current cheat version: 0". In other times, the cheats remain in the old version. When I try to see the installed cheats or manage them, sometimes the homebrew or atmosphere crashes (I'm not in applet mode). In atmosphere 1.2.0, everything was fine.

**Steps to reproduce the behavior.**: 
Turn on the wi-fi, open a game holding "R" and them open aio-switch-updater in album. After, try to update the cheats.

**Screenshots/Crash code/Crash reports**:
[01635261219_010049900f546000.log](https://github.com/HamletDuFromage/aio-switch-updater/files/7470473/01635261219_010049900f546000.log)
[01635449925_010000000000100d.log](https://github.com/HamletDuFromage/aio-switch-updater/files/7470491/01635449925_010000000000100d.log)
![2021110317185600](https://user-images.githubusercontent.com/93297718/140187154-004ec5b4-e383-4e81-a401-e218307b726c.jpg)
![2021110317183700](https://user-images.githubusercontent.com/93297718/140187158-8b9cb898-82b8-4deb-88fc-7b56796828f6.jpg)

**System Firmware Version and CFW Version**
AIO-switch-updater v.2.16.1
Atmosphere 1.2.2
Switch firmware 13.1.0

**SD card format**
FAT32.

**Comment by HamletDuFromage** [comment]
Sorry, I haven't replied because I had no idea what could be causing this, and I didn't have time to figure it out. Can you let me know if this still happens with the latest release of the app? Ideally on latest atmosphere too

**Comment by bjulio10** [comment]
I've tried the latest version of atmosphere and AIO. It looks like that the errors that I had in the previous versions have disappeared. This time, I only have an error with the option "Download CheatSlips.com cheats sheets". When I choose this option and I try to download an individual cheat, I get an error.

![01637431594_010065a014024000](https://user-images.githubusercontent.com/93297718/142737144-116bfc91-952a-420e-8906-b85544d419b8.jpg)
[01637431594_010065a014024000.log](https://github.com/HamletDuFromage/aio-switch-updater/files/7575029/01637431594_010065a014024000.log)

**Comment by HamletDuFromage** [comment]
It's actually quite odd. Can you try deleting config/aio-switch-updater/token.json? Is your internet very slow?
Also maybe it might be wise to check your SD card for corruption, because those error are quite odd

**Comment by bjulio10** [comment]
I've deleted /switch/aio-switch-updater and /config/aio-switch-updater folders, but the cheatslips option don't work. My internet is fine (wi-fi 5ghz and 250 Mbps) and my SD card isn't corrupted. The options "Download GBAtemp.net cheat archive (ver 11142021)" and "Download GBAtemp.net cheat codes" works fine. I can select a cheat in "Download CheatSlips.com cheat sheets", but when I press "B" to "Download cheats and go back" ant try selecting another game, I get a crash error. Now, I'm getting "Quota exceeded for today!" (need to increase my quota), but it doesn't crash. 
As everything is working fine (I don't use cheatslips, only gbatemp) and apparently it's an odd error, I'm going to close the topic. Thanks.

**Comment by HamletDuFromage** [comment]
Do you know which cheat you were trying to download when you got the error?

**Comment by bjulio10** [comment]
Any of them (pokémon brilliant diamond, shin megami tensei V, pokémon let's go pikachu...), but I think it was a problem with my cheatslips account and API token (and not with aio switch updater), because I've created another two accounts and both worked.

**Comment by HamletDuFromage** [comment]
Ah, it probably returns a response I don't properly handle. Welp, I'll leave it at that for now. Sorry for the rocky experience
