### ISSUE TITLE
The app can't be launch

### ISSUE THREAD

**Issue by sl1hck** [HamletDuFromage/aio-switch-updater#166]
Hi there,

Firstly many thanks for your works.

I added the contents to my fold /switch/ but I can't launch the app via the homebrew :

![image](https://user-images.githubusercontent.com/94802159/142778184-cba8d5c1-f436-42ed-b1c1-4b471816f8c2.png)

Could you please help me ?

Thanks in advance.

**Comment by HamletDuFromage** [comment]
You downloading the source code, you need to download the executable https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.16.2
