### ISSUE TITLE
program crashing with  downloading the 13.2 firmware

### ISSUE THREAD

**Issue by pka4916** [HamletDuFromage/aio-switch-updater#167]
I tried 4 times downloading FW 13.2
and when it unpacks  the program will crash.

any suggestions?

**Comment by HamletDuFromage** [comment]
That's odd. Does it crash instantly, does it extract a little then crash?

Can you send me the crash report? Also Do you have enough space on your SD card?

**Comment by pka4916** [comment]
It's crashing after about 95%.
When I download it again it seems to go through, but then fails on the check.

Also when I try to get into the firmware folder, atmosphere will crash as well.

I have 40gb free space on the card.
And using the latest atmosphere.

**Comment by HamletDuFromage** [comment]
You might have some corruption going on. I recommend checking for curruption before going any further. If all is fine, just delete the firmware folder

Are you using exfat or fat32?
