### ISSUE TITLE
[Feature Request] Adding this app to the Homebrew App Store

### ISSUE THREAD

**Issue by FamilyGuy0395** [HamletDuFromage/aio-switch-updater#169]
^

**Comment by HamletDuFromage** [comment]
It used to be on there, but the only way to have it back would be to hide the some features by default when downloading the app from the hb appstore, and make it so only by manually editing a config file you could get those features back

**Comment by FamilyGuy0395** [comment]
> 

Was it forcefully removed from the store?  I'm a bit confused what you mean.

**Comment by HamletDuFromage** [comment]
I pushed an update that would allow users to hide/unhide features from the app itself and the team informed me that it means they would take it off the AppStore. I was ok with that

**Comment by FamilyGuy0395** [comment]
So there's no way to get it on the App Store again?  I'll have to manually update the app via removing my SD card every time there's an update?

**Comment by SGTjulio** [comment]
@FamilyGuy0395 or tou can use ftp that way you don't have to keep removing your sd card or USB through hekate

**Comment by HamletDuFromage** [comment]
@FamilyGuy0395 @SGTjulio you can update the app from within the app, you just have to download it once

**Comment by FamilyGuy0395** [comment]
Oh I wasn't aware you could update it within the app, that's great!  Thanks for this really useful tool @HamletDuFromage!
