### ISSUE TITLE
Slow firmware download speeds

### ISSUE THREAD

**Issue by ded-doggo** [HamletDuFromage/aio-switch-updater#170]
**Describe the bug**
I'm getting 0.1 MB/s download speed when downloading the switch firmware, is there a known problem with it?

**To Reproduce**
Download any firmware

**System Firmware Version and CFW Version**
 - System Firmware: 13.2
 - CFW Version:1.2.5

**SD card format**
FAT32

**Comment by marvinjoa** [comment]
I do not think it is a bug but rather a limitation. Speed have been like this for me ever since. You're faster downloading the file on your PC, if youre able to find a link.

**Comment by HamletDuFromage** [comment]
archive.org downloads are just slow
