### ISSUE TITLE
Ryunjinx

### ISSUE THREAD

**Issue by Zlva** [HamletDuFromage/aio-switch-updater#171]
**What feature are you suggesting?**
It would be great if can make the app Ryunjinx compatible

**Describe alternatives you've considered**
at least a possibility to download the cheats

**Comment by HamletDuFromage** [comment]
If you're already on a computer, might as well download the cheats archive no? No to mention I assume cheats need to be a specific folder for the emulator, and an homebrew app ran in the emulator couldn't access your computers filesystem. 

That being said, you could easily write a python script that downloads and extracts the latest cheats
