### ISSUE TITLE
SigPatches Download broken

### ISSUE THREAD

**Issue by FaserF** [HamletDuFromage/aio-switch-updater#172]
**Describe the bug**
No download link can be fetched by this AIO Updater. Reason is, that the zip is now renamed and morged to one zip 
"Patches are now a single zip, as was warned, contents have not changed."
https://github.com/ITotalJustice/patches/releases/tag/13.2.1-1.2.6

**To Reproduce**
Go to the sigpatches download tab in the app.

**System Firmware Version and CFW Version**
 - System Firmware: 13.1.0
 - CFW Version: 1.2.6

**SD card format**
FAT32

**Comment by HamletDuFromage** [comment]
Fixed
