### ISSUE TITLE
Merging ROMFS... cp: illegal option -- u

### ISSUE THREAD

**Issue by nerirififi** [HamletDuFromage/aio-switch-updater#173]
Hello, 

I got this error when I try to compile your apps.

Merging ROMFS...
cp: illegal option -- u

Could you give me help for compilation please ?

**Comment by HamletDuFromage** [comment]
What OS are you using? The `-u` flag of cp, which allows to overwrite files in the destination folder isn't supported by your system. You could simple delete (with `rm -r`) the destination folders before the copy and remove the u flag for cp

https://github.com/HamletDuFromage/aio-switch-updater/blob/master/Makefile#L163-L165

**Comment by nerirififi** [comment]
i remove the problem using another computer, seems Mac M1 have a lot a problem when I compile.

I got another one, with application.cpp 31.10

fatal error glad/glad.h

I search on the net before, I see a website where I can create the file, but that need some settings.
How can I solve this issue please.

Thanks for your quick answer.

**Comment by HamletDuFromage** [comment]
Have you installed the required dependencies

https://github.com/HamletDuFromage/aio-switch-updater#build

**Comment by nerirififi** [comment]
yes for sure.

you got 1 problem on your make file.
I can't create rcm.bin at the beginning of the compilation, I remove this code of compilation. ( that will be cool if we can upgrade in rcm mode :)) 

https://github.com/HamletDuFromage/aio-switch-updater/blob/master/Makefile#L167-L168

After that, I make the compilation, like you say, and I got error when I compile 
application.cpp
So i compile borealis from another repo, that don't work with yours, and the nro borealis example works.
Then it create glad/glad.h
but I got a last error 

linking aio-switch-updater.elf
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/11.2.0/../../../../aarch64-none-elf/bin/ld: cannot find -lglad
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/libnx/switch_rules:80 : /home/admin/aio-switch-updater/aio-switch-updater.elf] Erreur 1
make: *** [Makefile:172 : build] Erreur 2


So I don't understand is it my glad.h the problem or ?

**Comment by HamletDuFromage** [comment]
Je suis pas sûr de comprendre. Mon makefile fonctionne. Tu as bien récupéré les submodules après avoir cloné le repo? Glad.h dépend de GLFW, donc si tu as installé ça, ça devrait marcher. 

Et tu pourras pas utiliser un autre borealis que ma fork pour compiler mon app

**Comment by HamletDuFromage** [comment]
Et l'histoire de créer un glad.h vide, c'est pas bon. C'est sans doute qui crée tes erreurs de linkage

**Comment by nerirififi** [comment]
qu est ce que tu appelles submodule ?
Non mon glade.h n est pas vide, sinon je ne pourrai pas creer borealisexample.nro

**Comment by HamletDuFromage** [comment]
Ouais mais je sais pas quel borealis tu compiles, moi j'ai une ancienne version, la nouvelle, dénommée yoga, n'utilise plus GLFW

Pour les submodules, tu peux chercher "git submodules" sur internet. Pour les choper dans ton repo local, suis ces instructions https://openmetric.org/til/programming/git-pull-with-submodule/

Essaie également "make clean" et recompile, peut être que t'as des objets pas correctement compilés

**Comment by nerirififi** [comment]
J'ai réussi a compiler le programme ouf !!!!
Il manquait une librairie, je l'ai trouvé à force de chercher.

En faites la modification que je veux faire est plutôt simple.
J'ai utilisé le fichier .json pour cacher le maximum de chose.

Je n'ai plus que 2 onglets.
Le truc c est que je voudrais totalement supprimé le visuel de Tools qui s'affiche sur la switch et avoir uniquement 1 seul bouton pour telecharger le CFW.
Est ce que tu saurais quel fichier il faut supprimer pour arriver a mes fins.

**Comment by HamletDuFromage** [comment]
`"tools": true` dans hide_tabs.json
