### ISSUE TITLE
Updating Atmosphere & Hekate

### ISSUE THREAD

**Issue by FamilyGuy0395** [HamletDuFromage/aio-switch-updater#175]
Wasn't really sure where to write this, who to write it to, how to contact the right people, etc., but here goes.  A new update for Atmosphere & Hekate went live and I decided to try out the AIO for the first time.  However, when doing so, it gave me like 5 or 7 prompts (I can't remember how many), and I really had no idea how to answer them.  I don't want to pick the wrong option and screw up my Switch.  Can anyone explain what each of these prompts means, and what the ramifications are for answering them with each option?  Thanks, I'm sorry if this is an inappropriate place to put this.  I tried reading the "README" on the GitHub page, and I don't see any instruction on what to do here.

**Comment by HamletDuFromage** [comment]
Default choice (whatever is the default highlighted option) is usually fine, although you really should read guides on switch hacking, you'll know what things meme.
Note that you have no chance of ruining your switch with my homebrew, worst case scenario you just do a clean install of atmosphere and you will have lost nothing
