### ISSUE TITLE
No new cheat archive since December 16th, 2021?

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/aio-switch-updater#176]
Are cheats just not being updated on GBAtemp anymore?

**Comment by HamletDuFromage** [comment]
There's been an upload in early January, but not where it usually is. It seems like matias3d hasn't been posting for a bit but maybe if someone asked him nicely on gbatemp he would upload it.

I could also do an exceptional manual upload I guess

**Comment by HamletDuFromage** [comment]
It's been updated today
