### ISSUE TITLE
cant open it

### ISSUE THREAD

**Issue by BrianRako** [HamletDuFromage/aio-switch-updater#177]
Hi, i drag and drop the file as you say but my switch only see it as a folder and not an application, any idea ?

**Comment by HamletDuFromage** [comment]
Are you sure you're downloading the release and not the source code? 
https://github.com/HamletDuFromage/aio-switch-updater/releases

**Comment by BrianRako** [comment]
AH, you right iam so stupid sorry to bother you

**Comment by HamletDuFromage** [comment]
No problem, glad I could help

**Comment by BrianRako** [comment]
hi i came back coz when i want install cheat i've juste one tab named show all the cheat but i cant dowload it

**Comment by HamletDuFromage** [comment]
I'm going to assume you're french, let me know if you're not
Je comprends pas ce que tu veux dire. Tu as un menu pour télécharger une archive de cheats, ainsi qu'une option pour les télécharger individuellement. Où est le problème?

**Comment by BrianRako** [comment]
mdr ça se voit a mon anglais je suppose, 

en gros quand je vais dans telecharger les codes de triche de gbatemp jai bien mon jeu pokemon perle afficher et quand je clique dessus j'ai juste un onglet "Montrer tous les fichier de triche" je n'ai pas d'option pour les télécharger

**Comment by HamletDuFromage** [comment]
En général ça veut simplement dire que la base de données n'a pas de codes pour ta version du jeu.
https://gbatemp.net/threads/pokemon-brilliant-diamond-shining-pearl-cheat-database.602559/ Ici tu devrais pouvoir trouver des codes plus à jour

**Comment by BrianRako** [comment]
Ah ok je pensais c'etait moi qui avais fais une mauvais manip, Merci
