### ISSUE TITLE
atmosphere not showing up as a download option 

### ISSUE THREAD

**Issue by needo37** [HamletDuFromage/aio-switch-updater#18]
atmosphere is not showing up as a download option 

Thank you!

**Comment by KaliXD** [comment]
Atmosphere no longer allows you to download and install updates when Atmosphere is already running

**Comment by KaliXD** [comment]
Atmosphere no longer allows you to download and install updates when Atmosphere is already running

**Comment by HamletDuFromage** [comment]
yeah, I need to work on a fix, sorry about that

**Comment by Tasemu** [comment]
@HamletDuFromage I've seen another atmosphere HB app that is working, not sure how they're doing it though. Btw just downloaded your app and love it!

**Comment by HamletDuFromage** [comment]
It's back
