### ISSUE TITLE
Cheatslips: "Could not fetch selected cheat codes/invalid token."

### ISSUE THREAD

**Issue by kedungs** [HamletDuFromage/aio-switch-updater#180]
**Describe the bug**
When trying to download cheats from cheatslips the message "Could not fetch selected cheat codes/invalid token." appears.

**To Reproduce**
Logged in to cheatslips on AIO switch updater and then accidentally clicked on "Reset Token" on cheatslips web page. Now the tokens do not match. There is no option to re-login to cheatslips on AIO or log out.

**Screenshots/Crash code/Crash reports**
No crash just the message "Could not fetch selected cheat codes/invalid token." when trying to download cheats from cheatslips because of token mismatch.

**System Firmware Version and CFW Version**
 - System Firmware: 13.21
 - CFW Version [Atmosphère 1.26]
![IMG_9822](https://user-images.githubusercontent.com/102693342/160911775-b906292b-cdeb-40b5-920b-8f238a4ca79b.jpg)
![IMG_9821](https://user-images.githubusercontent.com/102693342/160911794-65ca1613-45dd-4ee9-9483-a0eb48189b3b.jpg)

**Comment by kedungs** [comment]
Reinstalled aio-switch-updater.nro and somehow it still remembers the login information to cheatslips

**Comment by HamletDuFromage** [comment]
delete config/aio-switch-updater/token.json and log in again

**Comment by kedungs** [comment]
> delete config/aio-switch-updater/token.json and log in again

Deleting the token.json solved the issue. Thank you so much!
