### ISSUE TITLE
Dwonload another CFW Pack

### ISSUE THREAD

**Issue by genocidekyuubi** [HamletDuFromage/aio-switch-updater#181]
This is not a bug, but a question. Hamlet, if I want to use AIO Switch Updater to download and extract a CFW Pack like Sthetix's HATS, what should I do?

**Comment by HamletDuFromage** [comment]
Fill in https://github.com/HamletDuFromage/aio-switch-updater/blob/master/customPacks.json and place it in config/aio-switch-updater

**Comment by genocidekyuubi** [comment]
so you mean i have to fill it like this :

{
     "Name of pack": "https://github.com/stetix/HATS/releases",
     "Name of anther pack": "https://github.com/stetix/HATS/releases"
}

so you mean i have to fill it like this :

{
     "Name of pack": "https://github.com/stetix/HATS/releases",
     "Name of anther pack": "https://github.com/stetix/HATS/releases"
}

Its that true ?

**Comment by HamletDuFromage** [comment]
Like this:
```JSON
{
    "HATS 1.3.1": [https://github.com/sthetix/HATS/releases/download/1.3.1/HATS-1.3.1.zip"
}
```
If the releases were always named the same way (ie HATS.zip), you'd be able to use an url that always point to the latest release, like so: ttps://github.com/sthetix/HATS/releases/latest/download/HATS.zip
As it stands, you'd have to manually update the link each time (or ask the repo owner to change the release filenames)

**Comment by genocidekyuubi** [comment]
and assume that I managed to do it. Will the AIO Switch Updater immediately copy and replace the old files, or delete the old files first, then copy the new files?

**Comment by HamletDuFromage** [comment]
I don't understand your question. AIO will download the pack and extract everything where it's supposed to be

**Comment by genocidekyuubi** [comment]
I mean the method of AIO Switch Updater extracting files that have been successfully downloaded. Is the method is:
1. Immediately replace the old file
2. Or first delete the old file, then copy the file that has been successfully extracted.

Which method did AIO use to extract the files from that custom URL.

Thank you in advance for your answer 🙏

**Comment by HamletDuFromage** [comment]
New files overwrite old files. You can't run AIO if your system isn't booting
