### ISSUE TITLE
Support Korean translation

### ISSUE THREAD

**Issue by DDinghoya** [HamletDuFromage/aio-switch-updater#184]
**What feature are you suggesting?**
I would like to help with Korean translation.

**Describe the solution you'd like**
Provide "ko" folder -> aio-switch-updater/resources/i18n/ko

**Describe alternatives you've considered**
Korean translation of brls.json & menus.json

**Additional context**
N/A

**Comment by HamletDuFromage** [comment]
Sure! Feel free to make a PR, I'll merge it.

Take these files and translate them https://github.com/HamletDuFromage/aio-switch-updater/tree/master/resources/i18n/en-US
