### ISSUE TITLE
New mega.nz URLs crash app < 2.18.0

### ISSUE THREAD

**Issue by putnam** [HamletDuFromage/aio-switch-updater#190]
Versions of the app below 2.18.0 freeze if the user selects a Mega URL from the list, at least for firmware downloads. The bar freezes at 0% and the console must be manually powered off because the home button is locked out.

It would probably be good to version the manifest in some way so old versions don't crash on unsupported URLs

**Comment by HamletDuFromage** [comment]
The app should always be updated to its latest version. Worth mentioning that putting the switch to sleep and waking it up by pressing the home button 3 times should land you back to the home menu anyways

**Comment by putnam** [comment]
This may be a dumb question given there's an old closed issue about it -- but is the app meant to update itself? Mine has not done so or offered to do so when online.

**Comment by HamletDuFromage** [comment]
The app warns when there is a new update available, and can then be updated from the tools tab

**Comment by putnam** [comment]
OK, I think I wasn't warned for an update on 2.17 for some reason. Of course, I've updated and Mega links work fine now. It could still be beneficial to version assets since you use an online manifest component.
