### ISSUE TITLE
Download links not available with manual IP-Settings

### ISSUE THREAD

**Issue by Semsemboy** [HamletDuFromage/aio-switch-updater#193]
When using manual IP and DNS settings to use f.e. Lan Play the download links for none of the packages are shown. It says connect to wifi. the Settings are the following:

IP Address Settings:
IP Address: 10.13.XX.YY
Subnet Mask: 255.255.0.0
Gateway: 10.13.37.1

DNS settings (these are the 90DNS servers)
Primary DNS: 163.172.141.219
Secondary DNS: 207.246.121.77

Changing the settings back to automatic gets rid of the Issue
Maybe something could be implemented that doesn't hinder the usage of aio while having the settings.

FW: 14.1.1
CFW: AMS 1.3.2

SD card format
FAT32

**Comment by HamletDuFromage** [comment]
You're not actually connected to the internet when doing that, you are connected to a private network (created by your computer running lan-play) https://en.wikipedia.org/wiki/Reserved_IP_addresses#IPv4

This isn't a shortcoming of my app, what you're requesting cannot work.
