### ISSUE TITLE
missing line

### ISSUE THREAD

**Issue by yyoossk** [HamletDuFromage/aio-switch-updater#197]
In the menus.json file in the en-US folder, the line "not_found" is missing in the "payloads": {, entry
Is this due to a change?
But the Japanese translation shows it in the latest version

 "payloads": {,
    "not_found"

**Comment by HamletDuFromage** [comment]
Yeah, it was a duplicate message so I just removed it
https://github.com/HamletDuFromage/aio-switch-updater/commit/a1b9ab2f3b1e80cd1a48918c55e7d8f8d00d1e81

If it's still in the Japanese file, it's a mistake

**Comment by yyoossk** [comment]
ok
thx
