### ISSUE TITLE
"Update the app" Lock Up

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/AIO-switch-updater#2]
If you are on version 1.0.2 and try to run the "Update the app", it will get stuck at Extracting 5% currently.

**Comment by HamletDuFromage** [comment]
You're right, I had messed up with something. You can update to 1.0.3 (wait a for little while after being suck on 5% and quit with +) and then it should work fine.

Sorry about that, I've been introducing bugs trying to ignore .ini files, but it's (hopefully) all fixed

**Comment by Dantasstic** [comment]
Cheers, thanks for the fix! I appreciate this app and your hard work!
