### ISSUE TITLE
Japanese translation is not displayed

### ISSUE THREAD

**Issue by yyoossk** [HamletDuFromage/aio-switch-updater#200]
Japanese translation is not displayed

**Comment by yyoossk** [comment]
https://github.com/HamletDuFromage/aio-switch-updater/pull/201/commits/d03fd928e9f02a91d1740432780b0d8276311c49

**Comment by yyoossk** [comment]
plwase marge and update aioswitch

**Comment by HamletDuFromage** [comment]
sometimes you forget commas and it breaks the whole file.
If you can't test the app, please validate them with a website like such https://jsonlint.com/
