### ISSUE TITLE
Sigpatches are down due to DMCA

### ISSUE THREAD

**Issue by shyim** [HamletDuFromage/aio-switch-updater#206]
**Describe the bug**
The repo seems offline https://github.com/github/dmca/blob/master/2022/07/2022-07-28-nintendo-of-america.md

**Comment by TeJayH** [comment]
The new link for the patches are
https://jits.cc/patches
https://sigmapatches.coomer.party/sigpatches.zip

We're appealing the DMCA but if it doesn't get approved that's where I'm posting ours. I wouldn't update the tool to the new path until we know the results of the appeal just to save on effort.

**Comment by Dantasstic** [comment]
When will this be fixed to redirect to the new links?

**Comment by HamletDuFromage** [comment]
I've decided to stop providing sigpatches. The "sigpatches" tab has been replaced by a "custom download" tab

**Comment by mjyoung** [comment]
@HamletDuFromage Do you have an example of how we should configure the custom download json file for sigpatches?

**Comment by HamletDuFromage** [comment]
> @HamletDuFromage Do you have an example of how we should configure the custom download json file for sigpatches?

Not gonna provide support, but doing what you're trying to do is pretty explicit. Create custom_packs.json in /config/aio-switch-updater and fill it out with with your desired links
```JSON
{ "misc": { "display name": "https://example.com/file.zip" }}
```

https://github.com/HamletDuFromage/aio-switch-updater/blob/master/custom_packs.json

**Comment by mjyoung** [comment]
> > @HamletDuFromage Do you have an example of how we should configure the custom download json file for sigpatches?
> 
> Not gonna provide support, but doing what you're trying to do is pretty explicit. Create custom_packs.json in /config/aio-switch-updater and fill it out with with your desired links
> 
> ```json
> { "misc": { "display name": "https://example.com/file.zip" }}
> ```
> 
> https://github.com/HamletDuFromage/aio-switch-updater/blob/master/custom_packs.json

Alright, thank you! Also thank you so much for all that you do with this project :)

**Comment by krasi318** [comment]
what a shame :(
