### ISSUE TITLE
NRO file not included in "master" version of download

### ISSUE THREAD

**Issue by Theassassin2332** [HamletDuFromage/aio-switch-updater#207]
**Describe the bug**
downloading the ZIP file from the latest page downloads a "master" version which doesnt include the NRO file for it to launch on the switch, on the switch it just thinks it's a folder

**To Reproduce**
Go to Hamlets page and click on aio-switch-updater and download the ZIP file that is available, it gives a master version which can't launch.

**Screenshots/Crash code/Crash reports**
If applicable, add anything that might help explain your problem. Crash reports can be found under `/atmosphere/crash_reports`

**System Firmware Version and CFW Version**
 - System Firmware: 14.1.2
 - CFW Version: atmosphere 1.3.2

**SD card format**
FAT32

**Additional context**
in order to fix this for myself i just googled "aio switch download" and it's the second option for me, it says "releases" and that has the latest version from 5 days ago with just the NRO file to be able to put into my master folder and everything works on my switch now.

**Comment by HamletDuFromage** [comment]
Don't get the source code, get the release 
https://github.com/HamletDuFromage/aio-switch-updater/releases
