### ISSUE TITLE
Only a folder appears in atmosphere

### ISSUE THREAD

**Issue by HalcyonDoge** [HamletDuFromage/aio-switch-updater#21]
I downloaded, and pasted aio-switch-updater-master to switch/
But unlike the other apps there, this one only appears as a folder and can't be run. Is it because it doesn't have an nro? What am I doing wrong?

**Comment by HamletDuFromage** [comment]
You need to download the release, not the source code

https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/1.2.7

Also the the cfw updating is not available at the moment (and I should really write the fix) so don't be surprised by that

**Comment by HalcyonDoge** [comment]
Well that makes more sense.
Thanks!
