### ISSUE TITLE
preserve.txt not fully functional

### ISSUE THREAD

**Issue by FlyingBananaTree** [HamletDuFromage/aio-switch-updater#210]
**Describe the bug**

Doing a simple test with a custom pack update the preserve.txt feature only appears to work on directory paths and not files or directories as the readme states. 

Tested on the latest aio build 1e9f453

**To Reproduce**

Files tested:
```
sdmc:/test.png
sdmc:/test.txt
sdmc:/test/test.png
sdmc:/test/test.txt
sdmc:/test2/test.png
sdmc:/test2/test.txt
```

`preserve.txt` contents:
```
test.txt
test.png
test/test.txt
test/test.png
test2
```

Result: only the two files in test2 directory were preserved.

**System Firmware Version and CFW Version**
 - System Firmware: 14.1.2
 - CFW Version Atmosphère 1.3.2

**SD card format**
FAT32

**Comment by HamletDuFromage** [comment]
I just tried it and it worked for me. When using either `bootloader/sys/thk.bin` and `/bootloader/sys/thk.bin` inpreserve.txt, the file was not overwritten while updating hekate. 

I just pushed a commit that might fix be related to your issue though

**Comment by HamletDuFromage** [comment]
I had overwritten it with an empty file prior to testing. There's a few changes regarding extraction I'm gonna do, so it might fix your issues then

**Comment by PoloNX** [comment]
I see the problem. It check the last line not all lines. I think you can create a std::vector which contain all preserves files @HamletDuFromage

**Comment by HamletDuFromage** [comment]
@FlyingBananaTree is there a way we could chat (irc, discord etc) and try to debug this together? 
Because I checked again, added some print statements and I'm pretty sure it works on my machine

**Comment by HamletDuFromage** [comment]
This is my preserve.txt
```
bootloader/bootlogo.bmp
config/
switch/
atmosphere/
```

And this is what I get updating ams

```
[INFO] /atmosphere/ - preserved
[INFO] /atmosphere/config/ - preserved
[INFO] /atmosphere/config_templates/ - preserved
[INFO] /atmosphere/config_templates/exosphere.ini - preserved
[INFO] /atmosphere/config_templates/override_config.ini - preserved
[INFO] /atmosphere/config_templates/stratosphere.ini - preserved
[INFO] /atmosphere/config_templates/system_settings.ini - preserved
[INFO] /atmosphere/fatal_errors/ - preserved
[INFO] /atmosphere/flags/ - preserved
[INFO] /atmosphere/hbl.nsp - preserved
[INFO] /atmosphere/hbl_html/ - preserved
[INFO] /atmosphere/hbl_html/accessible-urls/ - preserved
[INFO] /atmosphere/hbl_html/accessible-urls/accessible-urls.txt - preserved
[INFO] /atmosphere/kip_patches/ - preserved
[INFO] /atmosphere/package3 - preserved
[INFO] /atmosphere/reboot_payload.bin - preserved
[INFO] /atmosphere/stratosphere.romfs - preserved
[INFO] /hbmenu.nro - overwritten
[INFO] /switch/ - preserved
[INFO] /switch/daybreak.nro - preserved
[INFO] /switch/reboot_to_payload.nro - preserved
```

**Comment by HamletDuFromage** [comment]
Ah right, I use Linux so that's why I didn't catch it. I'll fix that issue anyways. 
As for implementing a file browser for a feature that I'm sure most don't use, it probably won't happen. I might add an option to type in the paths from the console tho

**Comment by HamletDuFromage** [comment]
@FlyingBananaTree care to try this release?
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/9508200/aio-switch-updater.zip)

I tweeked the function to trim carriage returns
```C++
std::set<std::string> readLineByLine(const std::string& path)
{
    std::set<std::string> titles;
    std::ifstream lines(path);
    std::string line;
    if (lines) {
        while (std::getline(lines, line)) {
            if (line.size() > 0) {
                if (line.back() == '\r')
                    line.pop_back();
                titles.insert(line);
            }
        }
    }
    return titles;
}
```

**Comment by PoloNX** [comment]
Why did you reopen ?
