### ISSUE TITLE
V2.2.0 no more update sigpatches in list

### ISSUE THREAD

**Issue by Fitzzz90** [HamletDuFromage/aio-switch-updater#218]
**Describe the bug**
-Since updating AIO I no longer have the option to update sigpatches in my AIO menu.
-Have tried choosing to hide it in hide tabs menu to see if it acted in reverse, still not in list after relaunch
-Unhid in hide tabs menu, relaunched, still not in menu
-rebooted to payload, still not in menu

**System Firmware Version and CFW Version**
 - System Firmware: [e.g. 14.1.0]
 - CFW Version [Atmosphère 1.3.2|E]

**SD card format**
FAT32 

![20220924_204338](https://user-images.githubusercontent.com/114319293/192123554-37add10d-63b8-4e5a-9148-57ca605fc47f.jpg)

![20220924_204400](https://user-images.githubusercontent.com/114319293/192123558-b8e926d8-0e07-4517-a257-4e5d0a3ff434.jpg)

**Comment by HamletDuFromage** [comment]
This is by design. Links to sigpatches will no longer be provided. The custom tab replace it, where you can provide any link you wish

**Comment by Fitzzz90** [comment]
Oh perfect, sorry I must have missed that in patch notes, my apologies!

**Comment by Aida-Enna** [comment]
Don't forget to update https://github.com/HamletDuFromage/aio-switch-updater/issues/145 to reflect this - I was lost as well.
