### ISSUE TITLE
SX os 

### ISSUE THREAD

**Issue by chrisalex-dev** [HamletDuFromage/aio-switch-updater#22]
Hello,

I'm trying to use you all in one switch updater but it doesn't work on my swith.
I have to rename nro because if I don't it doesn't appear in hoimebrewmenu. Rename it make it to appar with a blue icon. I can lunch it but impossible to use all is blocked,just close it or relaunch to close again.
My switch firmware is under 10.2.0.
What do you think about that?
Thank you per advance.

**Comment by CallMeTeacherHuang** [comment]
We are the same
