### ISSUE TITLE
Didn’t update fusee, crash on boot

### ISSUE THREAD

**Issue by sjogro** [HamletDuFromage/aio-switch-updater#221]
Updated Atmosphere from 1.3.2 to 1.4.0, also updated to Hekate 5.9.0 when asked.
Rebooted into Hekate, selected payload: fusee from Hekate. 
Then, crash: wrong fusee version!

Will fix manually at my computer when I can. But didn’t expect this to happen…

Need to put fusee.bin into /bootloader/payloads

**Comment by HamletDuFromage** [comment]
Why are you chainloading? 
AIO can't be expected to know about everyone's specific use case. If you want to use a nonstandard way of launching Hekate, you must manually create copy_files.txt and copy atmosphere/reboot_payload.bin to your desire location. https://github.com/HamletDuFromage/aio-switch-updater#-update-cfw

**Comment by sjogro** [comment]
Oof I was not aware this is chainloading, I guess I never learned how to use Hekate the right way. Big eyeopener. /Hides in shame...
