### ISSUE TITLE
Continue button does nothing when updating Atmosphere

### ISSUE THREAD

**Issue by RenaKunisaki** [HamletDuFromage/aio-switch-updater#223]
**Describe the bug**
I'm stuck on a screen saying "The Switch will now reboot to a special payload in order to finalise the install." When I press any button or touch the Continue button there's an animation but nothing happens.

**To Reproduce**
Installed from HB App Store, selected update Atmosphere, selected Yes to all prompts.

**Screenshots/Crash code/Crash reports**
If applicable, add anything that might help explain your problem. Crash reports can be found under `/atmosphere/crash_reports`

**System Firmware Version and CFW Version**
 - System Firmware: 9.1.0
 - CFW Version: AMS 0.10.4|S

**SD card format**
FAT32

**Additional context**
I have no idea what I'm doing.

**Comment by RenaKunisaki** [comment]
Well, it did something: it bricked.

**Comment by HamletDuFromage** [comment]
You have a 2-year outdated ams. Do you use Hekate? Some breaking changes were introduced. Either way I would just update manually at this point

**Comment by RenaKunisaki** [comment]
I am using Hekate. Trying to manually update has just got me from "shuts off when starting Atmosphere" to "error screen when starting Atmosphere". At this point I have no idea what the problem is.

**Comment by HamletDuFromage** [comment]
> Notice about Atmosphere 1.0.0 and up: The fss0=atmosphere/fusee-secondary.bin in hekate_ipl.ini must be changed to fss0=atmosphere/package3. And make sure that atmosphere/contents folder does not have old Atmosphere components.

https://github.com/CTCaer/hekate/releases

**Comment by RenaKunisaki** [comment]
Right, just found that as well. Removing contents folder fixed it. Thanks for the help.
