### ISSUE TITLE
Inverse Options in 'Exclude games from receiving cheat updates'

### ISSUE THREAD

**Issue by bibliophilical** [HamletDuFromage/aio-switch-updater#224]
In the Tools>Cheat Menu, there's the 'Exclude games from receiving cheat updates' option. By default, all games cheats will be downloaded and in this menu, all games will have the option turned 'On' by default. I would like to request for a button to inverse the selection or have a button to quickly turn everything to 'Off' so that one could select only certain games to have their respective games cheat downloaded. (Rather than having to scroll to hundreds of games in the list to turn them 'Off')

**Comment by HamletDuFromage** [comment]
that's a good idea, I implemented it
