### ISSUE TITLE
Update bootloader payload on RCMloader

### ISSUE THREAD

**Issue by m0n4** [HamletDuFromage/aio-switch-updater#228]
**What feature are you suggesting?**
Updating the payload used by RCMloader directly from the Swich

**Describe the solution you'd like**
When upgrading bootloaders, it could ask the user if he wants to update his RCMloader at the same time.
He would then be invited to connect it to the dock station (with the cable provided).
When plugged the update continues as usual, after which the payload is replaced on the loader.

**Describe alternatives you've considered**
Adding a dedicated entry to the menu.

**Additional context**
When connected via its cable to the dock, the RCMloader is recognized as a mass storage device.
It is possible to browse its contents with the dedicated applications.
A text file is at the root indicating the path of the payload that should be executed.
The folder name can change but the file must always be named payload.bin

**Comment by HamletDuFromage** [comment]
I'm not willing to implement that
However if I were you, I would replace the payload in my RCMloader with a chainloader. Basically the payload always stays the same but launches a payload somewhere on your sdcard (`atmosphere/reboot_payload.bin` or `bootloader/update.bin` ). You can use the one aio uses for instance https://github.com/HamletDuFromage/aiosu-rcm

**Comment by m0n4** [comment]
That makes sense !
I didn't know it was possible to do that. 
Thank you for all this
