### ISSUE TITLE
AMS 0.15.0 crash

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/aio-switch-updater#23]
ver 37778 cheats install causes an Atmosphere crash

**Comment by HamletDuFromage** [comment]
fixed, the archive owner swapped from rar to zip archive so I had to update the script. Thanks for letting me know

**Comment by Dantasstic** [comment]
Cheers for the quick fix, confirmed no longer crashing :)

**Comment by dazuna** [comment]
Hey, I'm on SXOS and it crashes when it tries to extract the cheats. Might be the same problem?

**Comment by HamletDuFromage** [comment]
Yeah, he switched back to rar archives. Ive fixed it and tomorrow will write a check so that it doesn't happen again. Thanks though
