### ISSUE TITLE
How to use Cheats

### ISSUE THREAD

**Issue by Reo972** [HamletDuFromage/aio-switch-updater#230]
Hello all 😄 
Thank you for your work !
sorry if it's already been asked but how do you actually use cheats with aio-switch-updater plz ?

I installed the cheats correctly and I can see them in the list. But there is no option to activate them.
I tried to launch aiosu both via applet and album button, it says : 'restart via redirection method'.
Nothing in Tesla either.

Maybe adding some notes in Readme could help other noobs like me 🐤

**Comment by HamletDuFromage** [comment]
This should cover your needs https://www.cfwaifu.com/edizon-cheats/
