### ISSUE TITLE
Firmware 11.0.0? 

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/aio-switch-updater#24]
Firmware 11.0.0 is currently available on Darthsternie's site, but not through the app.

https://darthsternie.net/switch-firmwares/

**Comment by HamletDuFromage** [comment]
Not quite actually, I use the archive.org links

**Comment by Dantasstic** [comment]
So how long does that take to update usually?

**Comment by Dantasstic** [comment]
Ah ok, I wonder why it is only on MEGA on his site right now....

**Comment by HamletDuFromage** [comment]
https://twitter.com/Darthsternie/status/1335251798152667140
