### ISSUE TITLE
Could not find a download link

### ISSUE THREAD

**Issue by WollenMoth** [HamletDuFromage/aio-switch-updater#242]
**Describe the bug**
I get "Could not find a download link, make sure the Switch has access to the internet. If this problem persists, please open an issue on Github." on every download tab.
My Switch is connected to the internet using Automatic IP, 90DNS (USA) with 207.246.121.077 and 163.172.141.219 addresses, without a proxy and with MTU 1500.

**To Reproduce**
I open hbmenu from the Switch Gallery, it shows the Wi-Fi Icon and I open All-inOne Switch Updater in Applet Mode, then I go to any tab and I get the message I mentioned earlier.

**Screenshots/Crash code/Crash reports**
![2023031000473300-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/27463216/224243022-f275f5a7-2705-4e83-a479-f53c04fac0a7.jpg)
![2023031000474100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/27463216/224243036-2fb912cd-1bb2-4a6c-8dcb-6ea3ba69359b.jpg)
![2023031000474800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/27463216/224243047-42257347-2ec8-4be0-9bec-f390690fe072.jpg)

**System Firmware Version and CFW Version**
 - System Firmware: 15.0.1
 - CFW Version Atmosphère 1.5.0

**SD card format**
FAT32

**Additional context**
I tried connecting to other networks, restarting the console, uninstalling and installing aio-switch-updater, disabling background services and nothing seems to work.

**Comment by WollenMoth** [comment]
I have managed to get the links using my mobile network, but I tried to update the Firmware version and the app crashed, this is the log file.

[01678357455_010000000000100d.log](https://github.com/HamletDuFromage/aio-switch-updater/files/10939871/01678357455_010000000000100d.log)

**Comment by BeckysFootSlave** [comment]
DON'T use applet mode!
Title override!

**Comment by 414576872** [comment]
hi, add this  github host config(url:https://github.com/ButterAndButterfly/GithubHost/issues/495) to the hosts file (path:/atmosphere/hosts/ ), and restart.
