### ISSUE TITLE
"Could not find a download link" and "Couldn't obtain build ID" errors

### ISSUE THREAD

**Issue by mvergaraq** [HamletDuFromage/aio-switch-updater#244]
**Describe the bug**
Every tab shows "Could not find a download link", and when I try to download an individual cheat for a game it says "Couldn't obtain build ID". The app used to work for me before but it suddenly stopped working.

**To Reproduce**
Just open the nro.

**System Firmware Version and CFW Version**
 - System Firmware: 14.1.2 and also 16.0.1 (I updated my fw thinking it could be the cause)
 - CFW Version: Atmosphere 1.4.0 and also Atmosphere 1.5.1 (latest)

**SD card format**
FAT32

**Additional context**
Now EdiZon can't see most of my game's cheats, only a few games show, but in AIO all games say "Couldn't obtain build ID".

**Comment by HamletDuFromage** [comment]
This feature uses the internet to work. Are you connected to the internet? Do the other features of the app work?

**Comment by mvergaraq** [comment]
I'm happy to report I solved the issue, it had to do with 90dns. [This gbatemp post](https://gbatemp.net/threads/90dns-dns-server-for-blocking-all-nintendo-servers.516234/post-10073083) helped me, I just had to swap the dns1 with dns2, so it had nothing to do with AIO, sorry.
