### ISSUE TITLE
Disable Hekate and overwrite prompts from config file

### ISSUE THREAD

**Issue by i3sey** [HamletDuFromage/aio-switch-updater#252]
I propose to add the ability to disable the update offer hekate from config file.
This would be good for custom builds that already include modified  Hekate.

I also suggest doing the same for the overwrite proposal ini.

This will make life easier for users and help install the firmware in 1 click.

**Comment by Shipshinka** [comment]
I support this idea. (I do not know how to upvote here)

**Comment by Nephiel** [comment]
On that note: there is `preserve.txt`, where users can specify any file paths that should not be overwritten. What happens if the paths of the `.ini` files are in `preserve.txt`, but then the user selects `Yes` in the overwrite prompt during an update? Would those `.ini` files get overwritten anyway, or be preserved? Should they?

Having toggles to disable the overwrite prompts (for atmosphere and hekate at least) would be useful.

**Comment by HamletDuFromage** [comment]
@Nephiel yeah, preserve.txt should take prevalence over the prompt, in case you want to overwrite inis except for the ones you explicitly want to preserve.

@i3sey what would a modified Hekate be? Do you have an example?

**Comment by i3sey** [comment]
> @Nephiel yeah, preserve.txt should take prevalence over the prompt, in case you want to overwrite inis except for the ones you explicitly want to preserve.
> 
> @i3sey what would a modified Hekate be? Do you have an example? 

For example 4IFIR (popular overclocking atmosphere-based cfw). It contains a modified Hekate and this is its most important component.

**Comment by HamletDuFromage** [comment]
I'm probably not gonna add a way to disable the overwrite ini prompt. What would be the use case for it?

However I might add a new field for packs, or maybe a tag to put in the title (like `[PACK]`) that skips disables the hekate prompt

**Comment by i3sey** [comment]
> I'm probably not gonna add a way to disable the overwrite ini prompt. What would be the use case for it?
> 
> However I might add a new field for packs, or maybe a tag to put in the title (like `[PACK]`) that skips disables the hekate prompt

Thanks for listening to my words, I meant auto-confirmation of ini file overwriting. Sorry for my bad English, that's probably why you didn't understand me

**Comment by HamletDuFromage** [comment]
Nono your english is great and I understand what you want, but I'm asking why you want it. Does the 4IFIR pack update its ini files with every release?

**Comment by i3sey** [comment]
> Nono your english is great and I understand what you want, but I'm asking why you want it. Does the 4IFIR pack update its ini files with every release?

I consulted with the 4ifir community and came to the conclusion that autoconfirm overwriting is unnecessary. Thank you for your quick answers, I will look forward to implementing the hekate pass.
 Also noticed that autobuild doesn't work, I know how to fix it and will open a pull request soon. Also expect to add russian localization for aio, trying my best to help the project.
