### ISSUE TITLE
Translation of the application is not partially displayed

### ISSUE THREAD

**Issue by i3sey** [HamletDuFromage/aio-switch-updater#258]
**Describe the bug**
I made a fork of the app to translate it into Russian. After translating all the lines from menus.json, I saw that some pieces of text are still in English, although there is a translation.

**To Reproduce**
Go to the aio fork on my account and make sure the menus.json is correct.
download the build of the application from actions to see the lack of translations

**Screenshots/Crash code/Crash reports**
I'll attach it later

**System Firmware Version and CFW Version**
Doesn't matter, but 
 - System Firmware: 16.0.3
 - CFW Version 4IFIR 1.5

**SD card format**
FAT32

**Additional context**
after the problem is solved, I will create a pull request with a new translation of aio

**Comment by i3sey** [comment]
![2023060715181900-F1C11A22FAEE3B82F21B330E1B786A39.jpg](https://github.com/HamletDuFromage/aio-switch-updater/assets/86531179/4d3020cb-6678-4f94-a8d4-769d2babe40c)

![2023060715182300-F1C11A22FAEE3B82F21B330E1B786A39.jpg](https://github.com/HamletDuFromage/aio-switch-updater/assets/86531179/74304296-9184-447c-b609-39ac54229bc9)

**Comment by i3sey** [comment]
![image](https://github.com/HamletDuFromage/aio-switch-updater/assets/86531179/fb47de8f-65ff-4246-8c35-3d3f715a6143)

**Comment by HamletDuFromage** [comment]
You have an extra space here https://github.com/i3sey/aio-switch-updater/blob/568abf202a4c9b2c72469f7d603b1dbcfc34e524/resources/i18n/ru/menus.json#L9

`" cheats"` -> `"cheats"`

**Comment by i3sey** [comment]
Thank you
