### ISSUE TITLE
Extracting cheats crash's the system.

### ISSUE THREAD

**Issue by 91ajames** [HamletDuFromage/aio-switch-updater#265]
**Describe the bug**
Extracting cheats crash's the system. ver 2023-06-04 > 2022-08-24

**To Reproduce**
>Tools>Cheats menu>(5) D&ETEGBACA>Continue>100% Download>33% Extracting>Crash screen

**Screenshots/Crash code/Crash reports**
![IMG_4357](https://github.com/HamletDuFromage/aio-switch-updater/assets/24540531/2e181c46-8da5-4643-99ab-68b29d98e7b2)

[01687224668_010000000000100d.log](https://github.com/HamletDuFromage/aio-switch-updater/files/11795074/01687224668_010000000000100d.log)

[01687224668_010000000000100d_thread_info.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/11795100/01687224668_010000000000100d_thread_info.zip)

**SD card format**
FAT32

More than likely the same similar not fix issue here. ver 2022-08-24 < 2023-06-04
https://github.com/HamletDuFromage/aio-switch-updater/issues/212

**Comment by SiTWulf** [comment]
Same problem again

**Comment by MythicSylvia** [comment]
> Are any of you able/willing to help me debug with nxlink?

I am, because i am having same issue. How does nxlink work? never used it before

**Comment by 91ajames** [comment]
Its funny how you ask for help for which we never used these types of tools before and no clear instructions to use them with when more than a yr, anyone would think you would've fixed this by now. Seems like you have more than time to come back to since you're constantly updating your other guthub projects. Seems like this is just a dead project with the many bugs people had been posting with no indication on fixing them despite the different lives we all have.

**Comment by 91ajames** [comment]
Never used it and by now, I thought this would be fixed. How do you use this on your switch? does this crash for you as well?

**Comment by HamletDuFromage** [comment]
Hey @91ajames, if you're gonna type shit like that, maybe you ought to reach out when I ask you to contact me so I can look into your problem. 
![Screenshot_20231107-141845](https://github.com/HamletDuFromage/aio-switch-updater/assets/61667930/49b4e37d-5589-4eaf-b308-b3e306254060)

**Comment by Petric93** [comment]
I have the same problem. How did you solve It?

**Comment by johnkelvinliu** [comment]
Horizon v18.10.1, I have the same crashing problem when updating the cheat from AIO Switch updater, but the code is different.
0100024008310000 it is the Street Fighter 30th Anniversary Collection.
If I remove this 0100024008310000 folder from atomsphere/content/0100024008310000,
the crash code will become 0100000000001000.

**Comment by 91ajames** [comment]
> Hey @91ajames, if you're gonna type shit like that, maybe you ought to reach out when I ask you to contact me so I can look into your problem. ![Screenshot_20231107-141845](https://private-user-images.githubusercontent.com/61667930/284010827-49b4e37d-5589-4eaf-b308-b3e306254060.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODUwNTEsIm5iZiI6MTcyMTA4NDc1MSwicGF0aCI6Ii82MTY2NzkzMC8yODQwMTA4MjctNDliNGUzN2QtNTU4OS00ZWFmLWIzMDgtYjNlMzA2MjU0MDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIzMDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZjE5NDk4OTU5NDQwOGRhODI3Mzc5ZmM4MzljOTUxOGVmMjI1OGZkOWY1OGViNzQxN2Q3YzNlNjFiYWJkODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1t5ua9IvYc2yQ67UZnRJvM1RhLq05ABO_NuXLXpJ5eI)

I believe my friend was reeking havoc on my computer that day bc I'm not like that at all, I sorry for having this issue here. Nor do I see the comment at all. I haven't been on github in sometime until recently.
