### ISSUE TITLE
Mod downloading 

### ISSUE THREAD

**Issue by BDMCGaming** [HamletDuFromage/aio-switch-updater#270]
**What feature are you suggesting?**
I was thinking that a mod downloader could be useful.

**Describe the solution you'd like**
A tab to go mod browsing and download mods.

**Describe alternatives you've considered**
A tool instead of a tab or an option in custom downloads 

**Additional context**
It doesn't have to look directly in the database. It can be like a custom download where you have to input the link.

**Comment by HamletDuFromage** [comment]
Already exists

https://github.com/PoloNX/SimpleModDownloader
