### ISSUE TITLE
Feature request: Replace reboot payload but also copy latest fusee to a specific location

### ISSUE THREAD

**Issue by abjugard** [HamletDuFromage/aio-switch-updater#275]
**What feature are you suggesting?**
When updating Hekate it's great that the reboot payload can be replaced with Hekate.

However, I have Hekate configured to boot atmosphere by loading fusee.bin from `/bootloader/payloads/fusee.bin`.

When atmosphere is updated I need to update this payload in order for boot to succeed from Hekate, but I also want Hekate to be my reboot payload.

**Describe the solution you'd like**
I _think_ this is a common-ish configuration, but regardless, a solution that would work for me would be if AiO Switch Updater could be configured to automatically run a simple script after installing an atmosphere update, then I could just make a script that copied `/atmosphere/reboot_payload.bin` to `/bootloader/payloads/fusee.bin`.

**Describe alternatives you've considered**
- Add a button to download the latest fusee to a specific location.
- When replacing the reboot payload, keep a copy of the original as `fusee.bin` or other reasonable name, e.g. `reboot payload_orig.bin`.

**Comment by HamletDuFromage** [comment]
https://github.com/HamletDuFromage/aio-switch-updater#-update-cfw

You're in luck, it already is a feature! It's copy_files.txt

**Comment by abjugard** [comment]
> https://github.com/HamletDuFromage/aio-switch-updater#-update-cfw
> 
> You're in luck, it already is a feature! It's copy_files.txt

Hahaha, OK, I should have read the docs more carefully. Sorry for wasting your time!
