### ISSUE TITLE
payload.bin.aio doesn't rename to payload.bin

### ISSUE THREAD

**Issue by slslasher** [HamletDuFromage/aio-switch-updater#278]
![2023102523413700-DB1426D1DFD034027CECDE9C2DD914B8](https://github.com/HamletDuFromage/aio-switch-updater/assets/66656352/1863f397-1727-4389-af57-f9fc9e91e246)

After updating atmosphere, after restarting the switch. payload.bin.aio wont be rename to payload.bin which is why it is not booting.

The only workaround is press + when prompted and restart the switch manually.

Tested it on firmware 17.0.0

**Comment by BeckysFootSlave** [comment]
Had the same problem!

One solution was to rename the tegraexplorer.bin to payload.bin and put it into root of SD!
But that isn't really a solution because if someone has a modchip it will boot up TegraExplorer instead of hekate!

Now I compiled it myself with the path to payload in source!

**Comment by slslasher** [comment]
> Had the same problem!
> 
> One solution was to rename the tegraexplorer.bin to payload.bin and put it into root of SD! But that isn't really a solution because if someone has a modchip it will boot up TegraExplorer instead of hekate!
> 
> Now I compiled it myself with the path to payload in source!

is it possible to send me the compiled version?

**Comment by HamletDuFromage** [comment]
So from what I'm gathering, aio's payload doesn't rename payload.bin.aio to payload.bin? Is that a new issue with the latest AMS? I'm pretty sure it used to work but I can't test it

**Comment by nuguitar** [comment]
Hello thank you for your great work!

I had the same problem with a specific console unit(an OLED one).  <Other unit with the same setup is fine>
When trying to update AMS or HEKATE >>> after rebooting the console won't turn on, only a black screen with no payload.
Checked file on the route of SD card, there is "payload.bin.aio" and the "payload.bin" itself turned into something else that cannot inject.

Tried:
- Rebuid a new emummc from scratch(tried both file based and partition)
- System wipe
- Change mod chip
- Downgrade AIO to 2.22.0

**Comment by HamletDuFromage** [comment]
https://github.com/Atmosphere-NX/Atmosphere/commit/2ec3e141c7178c4ad570552bca4411946b88a22e

Might be due to this. I'll have to investigate

**Comment by monstrosities** [comment]
It worked fine on a Switch OLED here

**Comment by snupt** [comment]
Any solutions?

**Comment by HamletDuFromage** [comment]
Can someone with a patched switch contact me on discord? Message doodbye
