### ISSUE TITLE
Pls add internet time sync function for tinfoil https SSL error fix

### ISSUE THREAD

**Issue by Hitseditor** [HamletDuFromage/aio-switch-updater#28]

**Comment by HamletDuFromage** [comment]
Can you pleas elaborate?

**Comment by Hitseditor** [comment]
Sync the system time with internet coz stealth mode blocked the system update. There's a cfw called NX-ntpc but it doesn't work for some reason.
Setting correct system time is important coz when using tinfoil to download game from internet, it use https protocol. If your system time doesn't match internet time, it will cause connection failure.

**Comment by HamletDuFromage** [comment]
I've implemented nx-ntpc code but I didn't seem to work. Your best bet is to do it manually I think
