### ISSUE TITLE
the cheat section is gone

### ISSUE THREAD

**Issue by sirop2** [HamletDuFromage/aio-switch-updater#280]
Since i update the app the cheat section disappeared

**System Firmware Version and CFW Version**
 - System Firmware: [17.0]
 - CFW Version [Atmosphère 1.6.2]

**SD card format**
FAT 32

![image](https://github.com/HamletDuFromage/aio-switch-updater/assets/20713597/68d7728d-8e5e-47fc-ada6-efed062c6078)

**Comment by HamletDuFromage** [comment]
Outils -> hide tabs (cacher les onglets ?) 
Should be unrelated to an app update, maybe you've downloaded from a pack that hides some tab

**Comment by sirop2** [comment]
Thank you ❤️
