### ISSUE TITLE
Atmosphere crashes when "Add a custom link" clicked in specific condition

### ISSUE THREAD

**Issue by JulyIghor** [HamletDuFromage/aio-switch-updater#281]
**Describe the bug**
Atmosphere crashes when "Add a custom link" clicked in specific condition

**To Reproduce**

1) Create an empty folder SD/atmosphere/contents/0100000000001008/romfs/message  
2) Open All-in-One Switch Updater  
3) Select tab "Custom downloads"  
4) Press "Add a custom link"  
5) Enter random text, like "abcd" and press Submit+  

```
A fatal error occurred when running Atmosphere.
Program ID: 010041544d530000
Error Desc: std: abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000002cb2b08f.bin
Press POWER to reboot.
```

**Screenshots/Crash code/Crash reports**
[report_000000002cb2b08f.bin.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/13827738/report_000000002cb2b08f.bin.zip)

**System Firmware Version and CFW Version**
 - System Firmware: 17.0.0
 - CFW Version: atmosphere-1.6.2-master-f7bf379cf+hbl-2.4.4+hbmenu-3.6.0 

**SD card format**
FAT32

**Additional context**
It is may be Atmosphere bug and you can't fix it github.com/Atmosphere-NX/Atmosphere/issues/2263

**Comment by HamletDuFromage** [comment]
I can't seem to replicate it, and I'm on the same CFW and FW as you. If it really is an AMS bug, I can't do much anyway. Let me know if you learn more or if you have additional information I could use
