### ISSUE TITLE
AIO Switch Updater crashes upon start

### ISSUE THREAD

**Issue by baqlias** [HamletDuFromage/aio-switch-updater#284]
**Describe the bug**

I have just received a Switch OLED with Picofly set up. I have installed a few homebrew apps, including this one. All the others run as expected. When I start up this app, there is a black screen for a few seconds, and then a popup that simply says "The software was closed because an error occurred".  

**To Reproduce**
Simply start up the app!
[01708548285_01006a800016e000.log](https://github.com/HamletDuFromage/aio-switch-updater/files/14364817/01708548285_01006a800016e000.log)

**System Firmware Version and CFW Version**
 - System Firmware: 17.0.1
 - CFW Version: Atmosphère 1.6.2
 - Hekate 6.0.3

**SD card format**
FAT32

That's about all I can think of. I've tried the two newest versions of AIO, with the same result. Thanks for any help you can provide!

**Comment by HamletDuFromage** [comment]
It's a segfault, it seems to happen every now and then but I was never able to reproduce it
If you're willing willing to help me debug it, maybe we can hop on a chat and figure it out, though I can't promise anything. Weirdly enough this will probably eventually go away for you, oftentimes with a reboot

**Comment by baqlias** [comment]
Thanks for your reply! I have just discovered that the microSD card (128GB) is nearly full, with only 330 MB free space. Could that be a problem as well? I'm looking into how to copy everything over to a larger microSD card.

**Comment by HamletDuFromage** [comment]
330MB is plenty, I doubt that it's the issue. You could also try running the app in airplane mode, see if it has something to do with fetching the ressources

**Comment by baqlias** [comment]
I still get the error when running the app in airplane mode. I'm hoping this may eventually go away, as you said it might!

**Comment by baqlias** [comment]
AIO works fine now!  It's a great addition to a modded Switch. Thanks!
