### ISSUE TITLE
STHETIX CUSTOM FIRMWARE BUG ERROR 406 MESSAGE

### ISSUE THREAD

**Issue by AMGe350** [HamletDuFromage/aio-switch-updater#285]
**Bug Issue**
Dear Support, can I begin by complementing you on a fantastic piece of software. Ive been using it since day 1 with NO issues. A member of the homebrew community STHETIX has recently had his github DMCA'd! He has now moved his hats pack to another server, on the following link. https://link.sthetix.info/hats
As per normal I have programed in the above address & AIO-UPDATER is returning an ERROR 406. His previous link on his github page has worked fine over a number of years.

**To Reproduce**
1. Open AIO-UPDATER
2. Go down to section 6 Custom Downloads
3. Choose add custom link in the (DOWNLOADS CONTAINING THE ATMOSPHERE CUSTOM FIRMWARE
4. Type in the above link.
5. ERROR 406 message displayed

**Screenshots/Crash code/Crash reports**
Screenshots added.

**System Firmware Version and CFW Version**
 - System Firmwaree.18.0.0
 - CFW Version.1.7.0 on emunand

**SD card format**
FAT32
![2024040315533500-212AB1B1141DD2BDD9C73CB6FBF8C388](https://github.com/HamletDuFromage/aio-switch-updater/assets/68461372/a4745cf6-5219-4a93-866f-db3059109e57)
![2024040315533900-212AB1B1141DD2BDD9C73CB6FBF8C388](https://github.com/HamletDuFromage/aio-switch-updater/assets/68461372/449bacec-9bc0-4ccc-822a-07755d77809e)
![2024040315534400-212AB1B1141DD2BDD9C73CB6FBF8C388](https://github.com/HamletDuFromage/aio-switch-updater/assets/68461372/6d3badb8-ef14-407b-8277-905ca0d318ac)

**Additional context**

**Comment by HamletDuFromage** [comment]
https://link.sthetix.info/hats is not a direct link. https://codeberg.org/sthetix/HATS/releases/download/latest/HATS-1.7.0-2.zip would be a direct link to the release, but since the version is in the filename, that link would point to only that specific release

If you want to use my software, I suggest you contact the author and ask they name their release `HATS.zip`. You'll then be able to add https://codeberg.org/sthetix/HATS/releases/download/latest/HATS.zip as a custom link

**Comment by AMGe350** [comment]
My friend, Einstein was a GENIUS.....but your even better than him!!! I think the best solution is your link & for me to adapt it, everytime Ninty create an update that requires a different CFW version. Many thanks for your support & fantastic link. With regards

**Comment by HamletDuFromage** [comment]
The first field is the title, what you want the entry to appear as (eg HATS), the next one is the url (eg https://codeberg.org/sthetix/HATS/releases/download/latest/HATS-1.7.0-2.zip)

You entered the link as the as name, and entered nothing in the url field

**Comment by AMGe350** [comment]
Ive also deleted the software & reinstalled with NO luck. Ive also reached out to the author, who is seemingly NOT interested in updating his link, with your EXCELLENT suggestion!!

**Comment by HamletDuFromage** [comment]
You can try rebooting your console, and if it keeps on happening send me crash logs. I'll look into it

**Comment by HamletDuFromage** [comment]
It should be in `/atmosphere/`, in a folder called crash reports or something. I can't quite remember the exact name

**Comment by AMGe350** [comment]
Hi HamletDuFromage, have you any further updates please?

**Comment by HamletDuFromage** [comment]
It's a segfault that has been happening for a while and that I haven't been able to track down. I believe the bug is in UI library I use. The bad news is that I'm not gonna push a fix any time soon, the good news is that error eventually goes away on it own

**Comment by AMGe350** [comment]
Oh, O.K. My friend, truly if your struggling to fix it or locate it, then its no good me awaiting an act of God to take place!! If your struggling, then he has no chance of ever succeeding. Your kindness, & your skill have truly been appreciated during tbe course of today & please dont hesitate in dropping me a line.......should you require anything from the U.K side of things. With great regards

**Comment by AMGe350** [comment]
HDF, my friend Sthetix has now been closed down AGAIN on Codeberg!! He has now provided the above to download his Hat CFW! AIO is struggling with the following link he has provided. https://t.me/HATSPACK. Please coukd you advise further? With regards

**Comment by HamletDuFromage** [comment]
AIO really isn't suited for those scenarios. You Goild either install it manually or use good ol plain atmosphere. What's more, I cannot and do not offer support for third party packs, especially if they're DMCA struck
