### ISSUE TITLE
Update DBI

### ISSUE THREAD

**Issue by Hafidzgtg** [HamletDuFromage/aio-switch-updater#287]
**What feature are you suggesting?**
I asked for the dbi update feature... because updating dbi is easy without having to look for a PC/cellphone again... how come only kefir updater has dbi, that's not fair😅🙏🏻...

**Comment by HamletDuFromage** [comment]
I don't think I want to offer proprietary software. Also it's not really in the scope of the app anyway, something like the homebrew app store would work better.
That being said, DBI hasn't been updated in 6 months and looks pretty stable anyway

**Comment by Hafidzgtg** [comment]
oh.. okay🙏🏻..
i just wish could be here or on the hb app store..
