### ISSUE TITLE
Can't build 

### ISSUE THREAD

**Issue by PoloNX** [HamletDuFromage/aio-switch-updater#29]
I can't build it, when I try I have this big error
![Screenshot_20201227_235805](https://user-images.githubusercontent.com/57038157/103181236-69629380-489f-11eb-826e-8f976a1153d6.png)

**Comment by HamletDuFromage** [comment]
looks like you're missing libraries, in particular hid.h in that screenshot. Did you install devkitpro? I see you have another homebrew app on your github, can you compile that?

**Comment by PoloNX** [comment]
Yes I can compile it, but I have installed libnx too. I can't compile JC-color-swapper too. else where can I had hid.h ?

**Comment by HamletDuFromage** [comment]
Ah, apparemment, libnx a changé le fonctionnement de hid.h et le nom de ses fonctions. Je viens de mettre à jour libnx et j'ai le même problème que toi. Il faudrait que je me penche là dessus.
i tu utilise Discord, tu peux m'envoyer un message à Simple#8155 et on peut en discuter, mais je sais pas si je vais corriger l'app aujourd'hui. Si tu veux juste compiler l'app, le plus simple serait de retirer la fonctionnalité

**Comment by PoloNX** [comment]
Je vous ai envoyé une invitation

**Comment by HamletDuFromage** [comment]
updated code to reflect latest libnx changes. Now works
