### ISSUE TITLE
ERROR, when OLED using Custom Download 

### ISSUE THREAD

**Issue by zerofo** [HamletDuFromage/aio-switch-updater#290]
**Describe the bug**
ERROR, when OLED using Custom Download 
"mariko_payload_missing": "In order to update Atmosphère on patched Switches, your payload needs to be named \"payload.bin\" and should be at the root of your SD card."

**To Reproduce**
just download, everytime,

**Screenshots/Crash code/Crash reports**
![_20240805015521](https://github.com/user-attachments/assets/d226cf1f-bef0-413c-bec3-8e9e0af55168)

[crash_reports.zip](https://github.com/user-attachments/files/16488478/crash_reports.zip)

**System Firmware Version and CFW Version**
 - System Firmware: 18.1.0
 - CFW Version: 1.7.1

**SD card format**
exFAT

**Additional context**
using picofly chip

**Comment by HamletDuFromage** [comment]
What's the name and location of the payload used to boot your switch into cfw? Is it not /payload.bin?

**Comment by zerofo** [comment]
> **Describe the bug** ERROR, when OLED using Custom Download "mariko_payload_missing": "In order to update Atmosphère on patched Switches, your payload needs to be named "payload.bin" and should be at the root of your SD card."
> 
> **To Reproduce** just download, everytime,
> 
> **Screenshots/Crash code/Crash reports** ![_20240805015521](https://private-user-images.githubusercontent.com/46804648/354920059-d226cf1f-bef0-413c-bec3-8e9e0af55168.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTQ2MTAsIm5iZiI6MTcyMjc5NDMxMCwicGF0aCI6Ii80NjgwNDY0OC8zNTQ5MjAwNTktZDIyNmNmMWYtYmVmMC00MTNjLWJlYzMtOGU5ZTBhZjU1MTY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE3NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhY2RkNDA1ZjIxZjNiMjVmYzZhNzhmOGM2ZDRhYjE4NjhkMWVmNTA1MGUzZjJiZTc2NzFiMWFhNDU4OWI0NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s4h6Zb-YwJnlh97MJe5EtEAAX2r97t3Cuv454az9Zcc)
> 
> [crash_reports.zip](https://github.com/user-attachments/files/16488478/crash_reports.zip)
> 
> **System Firmware Version and CFW Version**
> 
> * System Firmware: 18.1.0
> * CFW Version: 1.7.1
> 
> **SD card format** exFAT
> 
> ## **Additional context**



> What's the name and location of the payload used to boot your switch into cfw? Is it not /payload.bin?

using hekate,, 
```
[CFW - emuMMC]
fss0=atmosphere/package3
emummcforce=1
atmosphere=1
icon=bootloader/res/icon_payload.bmp
id=atm
```
without /payload.bin, should i copy a hekate.bin and rename it to payload.bin?

**Comment by HamletDuFromage** [comment]
That's how I expect it to work, but with your current setup, what payload does your modchip use to boot? 

I'm not keeping up with switch hacking these days but maybe your specific modchip/configuration looks for a payload elsewhere?

**Comment by zerofo** [comment]
> That's how I expect it to work, but with your current setup, what payload does your modchip use to boot?
> 
> I'm not keeping up with switch hacking these days but maybe your specific modchip/configuration looks for a payload elsewhere?

i think remove that ['if'](https://github.com/HamletDuFromage/aio-switch-updater/blob/b61ed8407311ea35a2146893906fb8e7f1594f58/source/ams_tab.cpp#L43), should be a easyway. I tried it. It's working.
