### ISSUE TITLE
Updating custom pack doesn't reboot

### ISSUE THREAD

**Issue by JaySea77** [HamletDuFromage/aio-switch-updater#296]
I have a custom atmosphere pack that I wish to copy. After copying it, it tries to reboot, but gives the error that the payload file is missing. Bootloader/update.bin. When I check the sd card, the file does exist!

**To Reproduce**
Install a custom pack.

![image](https://github.com/user-attachments/assets/02abf855-6954-4fa0-91dc-9ab854019e4b)

**System Firmware Version and CFW Version**
 - System Firmware: 18.1.0
 - CFW Version ams 1.8.0

**SD card format**
FAT32

**Additional context**
Where should the update.bin be a copy from?

**Comment by HamletDuFromage** [comment]
Update.bin is a copy of your hekate payload. Does that file function as a payload? What custom pack is it? What if you try to update to bare ams & hekate through aio? 

It looks like my payload can't read your payload https://github.com/HamletDuFromage/TegraExplorer/blob/eb3098d311d707a0f706135ec4c271b329bce80a/source/main.c#L103-L110

**Comment by JaySea77** [comment]
Where does it get my hekate payload from? 
My custom pack is atmosphere and hekate and some other stuff.
Should I remove the update.bin and try again?

**Comment by HamletDuFromage** [comment]
it gets the hekate payload from your custom pack. That's why I'm thinking your pack may be broken, and why I'm asking to try installing hekate from the official release, through aio to see if it is. 
Removing update.bin and trying again may help, but I'm doubtful that it'll be any different.

SD card corruption could also cause the files to not be read correctly all the time

**Comment by JaySea77** [comment]
Where does it copy it from. What location and what filename?
I did remove the file and immediately after that it had a new update.bin, but the size was different than the one before it.

**Comment by JaySea77** [comment]
I notice that when I copy hekate it asks if I want to copy the file as /bootloader/update.bin.
It was the same filesize as the one I already had there.
Does it replace that file when installing a custom atmosphere pack?

**Comment by HamletDuFromage** [comment]
From hekate_ctcaer_x.x.x.bin, in the root from hekate.

>  I did remove the file and immediately after that it had a new update.bin, but the size was different than the one before it.
hekate automatically recreates it from the payload it's launched from

**Comment by JaySea77** [comment]
In my pack it is hekate.bin and not hekate_ctcaer_x.x.x.bin. Could that result in the file not being there?

**Comment by JaySea77** [comment]
I just installed my custom pack again after I did the hekate update and it reboots correctly.
After the reboot when I install my custom pack again. It reboots correctly again.
Are you sure it takes a payload from the zip and copies it to bootloader/update.bin?

**Comment by JaySea77** [comment]
Okay so I should rename it it hekate_ctcaer.bin and it will be copied? The size however was exactly the same as the latest hekate 107.08kb.
What can I do to check if my sd card is corrupted or not?

**Comment by HamletDuFromage** [comment]
if you're publisher of the pack, sure

I won't be able to assist you regarding sd card corruption. I'll close this issue since it doesn't seem to be inherently related to aio

**Comment by JaySea77** [comment]
Thanks for the help. The hekate filename helps for being on the latest hekate in update.bin. If I keep publishing the custom pack like I did, it would stay on the old version forever

**Comment by JaySea77** [comment]
I noticed that renaming the file gives me the question if I want to put the hekate paypload in the bootloader/update.bin and atmosphere/reboot_payload.bin.
The bootloader/update.bin is actualy updated just before the question. The reboot_payload.bin probably after reboot.
