### ISSUE TITLE
Remove the firmware update feature (firmware piracy

### ISSUE THREAD

**Issue by souldbminersmwc** [HamletDuFromage/aio-switch-updater#298]
**What feature are you suggesting?**
Removing firmware piracy feature

**Comment by AnthonieZ87** [comment]
... if that is how you feel why are you even here?

**Comment by HamletDuFromage** [comment]
While update files are copyrighted files that individuals technically don't have the right to share, they're also free (as in free beer) and can only be used on nintendo hardware. I do not host these files and if nintendo were to show any desire to get these off the internet, I'd remove that section from my software right away. However it looks like they don't mind.
