### ISSUE TITLE
Crash when trying to change pro controller color

### ISSUE THREAD

**Issue by drkz4ck** [HamletDuFromage/aio-switch-updater#32]
When accessing "Change the Pro controller color" in the Tools menu, if the "pc_profiles.json" downloaded from the master repository is placed in config>aio-switch-updater, the app will crash and a message instructing to reboot the console will be prompted.

The message displayed will depend on the current CFW running. This was tested with the lates SXOS and Atmosphere releases.

**Comment by HamletDuFromage** [comment]
You're correct, I formatted the json wrong. I pushed the fix, you can get the correct one from the fix now

**Comment by HamletDuFromage** [comment]
Also if you make some neat color profiles for pro-cons, don't hesitate to share them

**Comment by drkz4ck** [comment]
Thank you so much for looking it up! :)
I really apreciate the job you've done

**Comment by drkz4ck** [comment]
Hey, the error is still persisting. I'm not sure if you're checking the replies, so I'll wai a while before posting a new issue.

This time I took a screenshot of the error message, but I'm not sure if it'll help at all.

![photo5161329545146640765](https://user-images.githubusercontent.com/76820046/103596387-9a187d80-4edc-11eb-8229-d2004c1ebf2a.jpg)

**Comment by HamletDuFromage** [comment]
That's actually odd... Could you show me your pr_profiles.json?

**Comment by drkz4ck** [comment]
Wow, I just opened it with notepad and it was all over the place. Nothing like the code block it shows when opening the .json straight from the web browser.

Turns out downloading it directly wasn't doing any favor, so instead I extracted it from the "master" .zip and it worked just fine. Sorry for the mess and thanks again! :)

**Comment by HamletDuFromage** [comment]
The indentation shouldn't matter as long as the structure is right. I should really add some sorts of checks so that it doesn't crash if it's formatted wrong. Well at least I'm glad it works for you :)
