### ISSUE TITLE
crash on downloading/extracting contents.zip

### ISSUE THREAD

**Issue by OnkelM** [HamletDuFromage/aio-switch-updater#33]
Error Code: 2349-0008 (0x115d)
Firmware: 10.2.0 (Atmosphère 0.14.4-master-fa0df994)

**Comment by HamletDuFromage** [comment]
I've just tried and it worked, could you try again? Maybe you caught the archive right the moment it got updater (doubtful but you never know). If not there might be something wrong with a file within the archive

**Comment by OnkelM** [comment]
problem found, i had disabled internet access for the switch from the router and whitelisted only gbatemp and github.
it seems aio-updater was expecting something thats not available and this caused the crash...

the old cheats-updater was just complaining about cannot download something and did not crash like this new aio-updater.

**Comment by OnkelM** [comment]
found out with wireshark that i had to whitelist *.amazonaws.com also to prevent aio-updater crash...
where this mentioned in the readme ?

**Comment by HamletDuFromage** [comment]
Ah yeah, I probably handle exceptions less throughouly. I'm going to close the issue, not sure I can consider that a bug per say

**Comment by HamletDuFromage** [comment]
Ah, it's because github uses amazon services, so to download the archive hosted there, you apparently need it.
