### ISSUE TITLE
FEATURE - Update CFW links manually with a button

### ISSUE THREAD

**Issue by EmreTech** [HamletDuFromage/aio-switch-updater#36]
Pretty much, I would like a button in the Extras tab that refreshes the links manually. This is useful since you don't have to wait 3 hours to download a new version of Atmosphere/Hekate.

**Comment by HamletDuFromage** [comment]
I'm afraid that wouldn't do anything. The 3 hours timeframe is the frequency at which I check if there are new links, server-side. For instance this page https://hamletdufromage.github.io/switch-cfw/cfw.html gets updated every 3 hours. I opted to do it that way so it could be more robust, and so I can fix links without having to push an update to the app

**Comment by EmreTech** [comment]
Oh. Can you at least maybe change when the page is updated to 1 or 2 hours? I feel like 3 hours is too long

**Comment by HamletDuFromage** [comment]
Is it though? There is about one update every month I'd say, so the majority of times I'm checking, there is nothing new. I think it's fine to not update the very minute a new AMS comes out

I'm also using a free VPS for that, so I don't want to abuse the resources given to me

**Comment by EmreTech** [comment]
Okay yeah, that's a good point. Thanks for informing me about this.

**Comment by HamletDuFromage** [comment]
No worries. If I find a better way to do it I'll implement it, but I think this is good enough for the time being
