### ISSUE TITLE
Request.  Feature request

### ISSUE THREAD

**Issue by fennectech** [HamletDuFromage/aio-switch-updater#37]
I host a dns server on my computer that permits using Nintendo network with cfw while still blocking telemetry    Would you consider adding it to the DNS thingy?   IP is 47.7.201.195.  If possible could you derive the IP fro my DDNS domain.    Fennectech.dynserv.org

**Comment by HamletDuFromage** [comment]
You can add it yourself by placing internet.json in the root
https://github.com/HamletDuFromage/aio-switch-updater/blob/master/internet.json

Prolly won't add it to the defaults though, most people wouldn't know what it is
