### ISSUE TITLE
Atmosphere crash

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/aio-switch-updater#38]
AIO 1.5.0, AMS 0.17.1, HOS 11.0.1

If you have no cheats currently installed, download cheats, and then while still in the app you go to "View Installed Cheats" this causes an Atmosphere lock up requiring a device reboot.

also, may as well fix the spelling of "Dowload payloads" while you are under the hood :)

**Comment by HamletDuFromage** [comment]
I can't manage to replicate, both in applet mode and full ram access. I'll fix the typo though

**Comment by HamletDuFromage** [comment]
typo is fixed and 1.5.0 was shadow updated. Could you let me know if you can replicate the cheats issue?

**Comment by Dantasstic** [comment]
No longer occurring for me, thank you!

**Comment by HamletDuFromage** [comment]
Didn't do anything, so not sure why it happened in the first place, but I'll take it

**Comment by Dantasstic** [comment]
haha I say we blame it on AMS then XD
