### ISSUE TITLE
[Localization request] Please consider to add Traditional Chinese translation for AIO

### ISSUE THREAD

**Issue by qazrfv1234** [HamletDuFromage/aio-switch-updater#39]
Hello,

According to the app interface(v1.5.1), I produced a corresponding Traditional language files compressed zip file can give
your reference as an attachment.

Many thanks,
Leo

[zh-rTW.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/5897297/zh-rTW.zip)

**Comment by HamletDuFromage** [comment]
Hello!
Added it, thanks a lot! It's in v1.5.1
