### ISSUE TITLE
Prominent update info

### ISSUE THREAD

**Issue by Dantasstic** [HamletDuFromage/AIO-switch-updater#4]
I have some suggestions :)

- have the app display on the starting page whether or not itself is the newest version (perhaps in brackets saying "Update available" right after the currently installed version number, or even just on the About page) , so we don't have to scroll down to Tools to see if there is a new version of the app to download.
- remember which cheats package number I have already installed (if done so by the app before) so I can compare the numbers and see if I need to grab a new cheat package. I can't remember that 5 digit code all the time to know if it has changed from what I last installed.

**Comment by HamletDuFromage** [comment]
All done in 1.1.3

**Comment by Dantasstic** [comment]
You are a total badass!
