### ISSUE TITLE
A fatal error has occurred when running Atmosphere

### ISSUE THREAD

**Issue by Roll2Me** [HamletDuFromage/aio-switch-updater#40]
Hello, whenever I use an option in the AIO Switch Updater, such as updating the app to the current version, updating the signpatches for 11.0.1 (I'm currently on this firmware + atmosphere 18) or downloading and then it hits the extraction for cheats (as well as signpatches or app update) it crashes and screen goes black and I get error code.

Program ID: 0100000000000004.
Error Desc: std::abort() called (0xffe)

**Comment by HamletDuFromage** [comment]
Which version of the app are you using, and are you using it with full ram access?
Could you please try updating to the latest version manually and try again?

**Comment by Roll2Me** [comment]
Newest version, I redownloaded and placed on SD card.  **How do I ensure full ram access?**  I have AMS18.0 downloaded today and updated it along with 11.0.1 today.  I have more than 1 microSD card and this one has the issue even though I did same steps as the other ones with same sysmodules.

**Comment by HamletDuFromage** [comment]
full ram access is when you launch the hbmenu by pressing R when launching a game. Can you disabling the sysmodules anyways, if only for testing? You can easily do this with https://github.com/WerWolv/ovl-sysmodules if you don't have it already.

Do you have mission control on?

**Comment by Roll2Me** [comment]
Yes I always launch homebrew via RB right bumper when launching game.  Yes I have Mission Control on.  I turned it off via sysmodules and now it extracts files without crashing.  So its a memory issue as you mentioned earlier? I'm not sure why my other SD card with same exact items installed didnt experience this issue.

**Comment by HamletDuFromage** [comment]
I'm looking into it, not quite sure what it is yet. I'll keep this issue open and keep you updated if I learn more

**Comment by HamletDuFromage** [comment]
Did you have emuiibo on too?

**Comment by bachato** [comment]
Mission Control I couldn't turn off, and I have sys-ftpd-light installed, when I turned it off I didn't have a crash.

**Comment by HamletDuFromage** [comment]
it would seem that it's when too many sysmodules are enabled then. For me, it works fine with both missioncontrol and sys-ftpd-light enabled. I'll try to see where I can shave off resources. That's not something I cared about too much while writing the app but admittedly there are some parts that could use a rework

**Comment by Roll2Me** [comment]
Yeah I had emuiibo/tesla overlay/edizon/mission control installed.  Although Emuiibo was technically already off until I activate it for amiibo and only tesla overlay/edizion and mission controll were on.  @bachato you turn mission control off by toggling it off for auto load and restart.

**Comment by HamletDuFromage** [comment]
I tested it more, and it's definitely an issue when too many sysmodules are running

**Comment by bachato** [comment]
@Roll2Me thanks

**Comment by HamletDuFromage** [comment]
fixed it (for real this time)
You should be able to run this with as many sysmodules as you want
