### ISSUE TITLE
Feature Request - Add an opt-out for downloading sigpatches

### ISSUE THREAD

**Issue by EmreTech** [HamletDuFromage/aio-switch-updater#41]
Hello, I'm back. This time, I feel like there should be an opt-out for the downloading sigpatches. Some people would use this program if it doesn't have to relate to piracy. What I mean as an "opt-out" is possibly a different version of the nro, but it can't download sigpatches at all.

**Comment by HamletDuFromage** [comment]
I would say "just don't click", but I'll consider it

**Comment by HamletDuFromage** [comment]
Next version will have a way to toggle tabs

**Comment by EmreTech** [comment]
Okay great! I'm excited to try it out!

**Comment by HamletDuFromage** [comment]
Version 2.0.0 is out and that's in it. you put this file in config/aio-switch-updater, or toggle the tabs out from the tab menu
[hide_tabs.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/5937440/hide_tabs.zip)

**Comment by EmreTech** [comment]
Thank you so much! I really appreciate it
