### ISSUE TITLE
How can I log in to CheatSlips in app?

### ISSUE THREAD

**Issue by SakuraSaku0033** [HamletDuFromage/aio-switch-updater#42]
I can't find log in menu in app

How can I log in?

**Comment by HamletDuFromage** [comment]
Just click on "download cheatslips cheat sheets" and it will open a keyboard prompting you with the your email address and password.
If you don't have a cheatslips account already, make one here https://www.cheatslips.com/register

**Comment by SakuraSaku0033** [comment]
I can't see keyboard prompte just 'Couldn't retrieve token,make you enter you login properly' message

**Comment by HamletDuFromage** [comment]
that's odd that the keyboard doesn't show up... Which cfw/version are you using?

**Comment by SakuraSaku0033** [comment]
sorry I work in applet mode. I think it is the problem.
11.0 version

**Comment by HamletDuFromage** [comment]
yeah, but in applet mode works for me.. Weird stuff
