### ISSUE TITLE
Support AMS 0.18.0 dns_mitm to update hosts file

### ISSUE THREAD

**Issue by popy2k14** [HamletDuFromage/aio-switch-updater#43]
As you may read, AMS 0.18.0 is released an supports a new dns_mitm module.

With this a custom hosts file can be used. 

Is it possible to implement a feature to update it with your amazing app to block all n8nja's?

Thx

**Comment by HamletDuFromage** [comment]
Probably not tbh, I can't really think of an elegant way to do it, and you only need to do it once anyways. I think it's better you do it from a computer. I'll keep this issue open in case I change my mind

**Comment by popy2k14** [comment]
Done already :-) was just an idea.
