### ISSUE TITLE
The Hekate updater doesn't ask to replace the reboot_payload with Hekate's payload

### ISSUE THREAD

**Issue by MattKimura** [HamletDuFromage/aio-switch-updater#44]
One thing I like about the aio updater from jits is that when updating Hekate, it asks if you want to replace reboot_payload.bin with hekate's bin file. I like having Hekate as my reboot payload since it's more convenient for switching between sysMMC and emuMMC or swapping SD cards. The only thing that the Hekate updater asks about in this aio updater is if I want to replace any .ini files. This means that my reboot_payload remains as Atmosphere which is what I don't want.

I love how you have a tools section for downloading fusee-primary to the bootloader/payloads/  folder. That covers one of my needs while updating, only thing left is to create a way to replace the reboot_payload with hekate's payload. Then it will be a perfect solution for updating. Right now I have my friends using both your aio updater and the jits updater, just to be able to use the Hekate updater on the other app to replace reboot_payload. I really don't want to have to use two different aio updaters because the main one that I use (yours) is missing a key feature that the other app has.

But thanks for putting so much work into this updater, it really has a lot of potential to become the best of the best. I really appreciate it and so do my friends who aren't so great at updating manually.

**Comment by HamletDuFromage** [comment]
Hello!
My updater copies the Hekate payload to bootloader/update.bin, and reboots to it when you finalize the install. If you wish to set Hekate as reboot_payload.bin, you may go to the "inject payload" section and press x to set any payload as reboot_payload
