### ISSUE TITLE
Downloading cheats error

### ISSUE THREAD

**Issue by jowedski** [HamletDuFromage/aio-switch-updater#47]
![20210213_031245](https://user-images.githubusercontent.com/78979881/107811659-7ed94180-6da9-11eb-9a4f-abf304fb3233.jpg)
I am unable to download cheats and during the extracting phase the above error happens. I have 11.0.1|AMS M.18.0|S

**Comment by HamletDuFromage** [comment]
right, sorry about that. It's fixed now. I changed the way to update cheats on the backend and there was a little bug, but now it should be good

**Comment by jowedski** [comment]
Appreciate the quick response and fix on this! You rock!
