### ISSUE TITLE
Updating Atmo/Hekate on a Mariko + SX Core / Spacecraft-NX Crashes on boot

### ISSUE THREAD

**Issue by IBNobody** [HamletDuFromage/aio-switch-updater#49]
I'm running HOS 11.0.1 and was running Atmosphere 0.17.1 and Hekate 5.5.3. I have a Mariko switch, and I have an SX Core installed running the latest build of the open source Spacecraft-NX replacement firmware. I'm running with sys-clk and sys-ftp lite (edit: and Tesla).

I installed and used your nsp redirect to launch the latest version of the AIO updater.

I used the AIO updater to install Atmosphere 0.18.0, Hekate 5.5.4, and sigpatches. I noticed that when I installed Atmo, the AIO updater mentioned something about a special payload was going to be run during next boot to replace Atmo. 

I figured this was going to break things, and I was right. 

A manual reboot took me back to Hekate which chainloaded Atmo. I encountered a fatal error (Program ID: 0100000000000008 Error Desc: std::abort() called (0xffe))

I was able to repair the issue by doing two things.

1. I renamed the sdcard:\hetake_ctcaer_5.5.4.bin to sdcard:\payload.bin
2. I reinstalled Atmo 0.18.0 by hand.

I _suspect_ that your AIO updater wants to boot to RCM and trigger a payload to finalize the Atmo install. Is that correct? If so, that's not how things work on Mariko SX Core/Lite units running Atmosphere (regardless of what firmware is running on the SX Core/Lite). The SX Core is going to look for sdcard:\payload.bin and launch that.

For Mariko units, you need to swap out the sdcard:\payload.bin file with your intermediary payload, and then issue a hard reset for the switch. Your payload does its thing, and then it needs to replace sdcard:\payload.bin with a copy of either fusee_primary.bin or hetake_ctcaer_x.x.x.bin.

If you need a guinea pig to validate this, I can do that for you.

**Comment by HamletDuFromage** [comment]
I was worried about the mariko stuff and how it would handle it. I would disable the option to update AMS and inject payloads altogether but I don't even know how to check whether a switch is patched or not. 

You're correct about the rcm payload being injected to finalize the install and your method would probably work. It is quite a bit clunky though, and to work I'd need to know if the switch is chipped anyways. Maybe I will ask for your help after I learn more about all this. Thank you
