### ISSUE TITLE
The app cannot connect the net if I build and output an app 

### ISSUE THREAD

**Issue by tiansongyu** [HamletDuFromage/AIO-switch-updater#5]
I want try to add a Multi-language version then I build the app ,but the app cannot connect the net .
I know the release app is fine ,it can connect the net ,but other app is not okay .

You can download the app from the [Actions](https://github.com/HamletDuFromage/AIO-switch-updater/actions/runs/284996668) that you created, all of these by the Actions can not connect the net .

I don't know why ,please help me

**Comment by tiansongyu** [comment]
Hey.   The release version is 8+mb，but other version is just 7.83mb，I think the source may lost something？i don't know 
:D

**Comment by HamletDuFromage** [comment]
This happens because you used Incognito/Incognito_RCM or wiped the PRODINFO partition. LibNX SSL backend requires a valid SSL certificate which is stored in PRODINFO partition.
You can either restore your PRODINFO, compile the app with an old version of switch-curl that still supports invalid SSL certificates, or compile it with https://github.com/eXhumer/switch-ex-curl instead

**Comment by tiansongyu** [comment]
Thank you so much!!
That will solve my problem
Actually lots of people use incognito to wipe PRODINFO
And then i can build a multi language version for Chinese people .
I have some free time and I think I will PR the multi language version for this app.I LIKE this app.THanks for your work.
Have a good day!

**Comment by HamletDuFromage** [comment]
Yeah, I use prodinfo blanking too 
Glad you like it and good luck on the multi-language work, I hope you can navigate my messy code haha

**Comment by tiansongyu** [comment]
I have add a multi-language option for many switchbrew app.and PR them . I will handle it .but i dont have a app belong to me. 
Actually i want to write an app just like this app before i find this.
It's pretty much what I thought it would be.haha.
