### ISSUE TITLE
NSP Forwarded AIO Instance thinks it's still in applet mode - Unable to launch web browser

### ISSUE THREAD

**Issue by IBNobody** [HamletDuFromage/aio-switch-updater#50]
I'm running HOS 11.0.1/Atmosphere 0.18.0. I have a Mariko switch. I'm running with sys-clk (and Tesla overlay).

Regardless of whether I launch AIOSU from its own NSP forwarder (that you provided) or from the Homebrew menu launched from my own Homebrew NSP forwarder, AIOSU still thinks I'm in applet mode and won't let me launch the web browser.

**Comment by HamletDuFromage** [comment]
This is normal behavior, you can't launch the web browser through forwarders. I'll change the error message though

**Comment by IBNobody** [comment]
A change to the error message would solve the problem for me!
