### ISSUE TITLE
AIOSU 2.2.1 Crashes when launching in airplane mode

### ISSUE THREAD

**Issue by IBNobody** [HamletDuFromage/aio-switch-updater#51]
(Sorry for the barrage of issues.)

I'm running HOS 11.0.1/Atmosphere 0.18.0. I have a Mariko switch. I'm running with sys-clk (and Tesla overlay).

If I launch AIOSU using any method (NSP Forwarder, NSP Forwarded Homebrew Menu, Regular title override Homebrew Menu, and Homebrew Menu Applet mode) with airplane mode enabled, AIOSU either force-closes or crashes Atmosphere.

(I normally run in airplane mode, and I often forget to disable it when running homebrew.)

**Comment by HamletDuFromage** [comment]
That's odd, doesn't crash on my end... Might be some Mariko specific stuff. If you have some crash reports, I could take a look at them

**Comment by IBNobody** [comment]
All methods other than applet mode cause the black-screen Nintendo-style errors. Applet mode causes an Atmosphere error.

[crash_reports.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/5977141/crash_reports.zip)

https://i.imgur.com/KolEbNt.jpg

(Not sure where Atmosphere logs that error info. Only \Atmosphere\crash_reports had any files.)

**Comment by HamletDuFromage** [comment]
Would you be willing to message me on discord @Simple#8155? I can try to give you a new version and see how we could debug it

**Comment by HamletDuFromage** [comment]
Magically fixed apparently
