### ISSUE TITLE
[Localization updated] Traditional Chinese langs for v2.3

### ISSUE THREAD

**Issue by qazrfv1234** [HamletDuFromage/aio-switch-updater#52]
Hello,
the attachment for v2.3(the latest menus.json )
[zh-rTW_v2.3.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/5977140/zh-rTW_v2.3.zip)

Many thanks,
Leo

**Comment by HamletDuFromage** [comment]
Thanks a lot! I'll update it :)
