### ISSUE TITLE
Request/Suggestion expand the hide tabs capabilities

### ISSUE THREAD

**Issue by pixeltester** [HamletDuFromage/aio-switch-updater#53]
Thank you for adding the hide tabs capability! I wanted to ask if you would consider expanding the capability of this feature to include the ability to hide options from the Tools menu. I'd actually like to hide the 'Hide tabs' menu after making the changes to make sure it's completely hidden to other people that use my Switch so that they can't reactivate that. I'd also like to block off a couple of the other options from that menu.

My suggestion would be to make this something where you can edit the json on your computer to make sure it's secure and not able to edited on the Switch itself, for example allow this to work: "Tools - Hide tabs": false

After that the other selections would still be parsed from the json but the Hide tabs menu itself would now be hidden. I hope that made sense, thank you!

**Comment by HamletDuFromage** [comment]
Sure, I'll do that. 

Although this part I didn't understand
> I'd also like to block off a couple of the other options from that menu.
Which menu are you talking about? 

My only problem with it though, is that it would hide the "download app update" item that is pretty important, and getting around it, while perfectly possible, wouldn't be very elegant

**Comment by pixeltester** [comment]
Great! What I meant was being able to hide individual items from the "Tools" menu, so for example:

"Tools - Hide tabs": true
"Tools - Web Browser": true

I'm not sure where your "download app update" item is looking at the app now but would that approach cover it?

**Comment by HamletDuFromage** [comment]
Ah I don't know about that, it's going to be quite a bit ugly.. What specifically are you afraid off, kids rebooting to a payload?

As for the second nro, it's because I used to need to name my releases aio-switch-updater-vx.x.x.nro, so I'm shipping this one for now to not break the app updates for users of the ancients version. You don't need to worry about it really

**Comment by pixeltester** [comment]
Hmm perhaps you're misunderstanding the request? You have the option already to hide the menus that mess with cfw files which is great but I was asking for the ability ok top of that to hide the option that will unhide them, which is: Tools menu / Hide Tabs

If the main user of the system can hide that option it would prevent other casual users of the system (kids, friends, dog or whatever) unhiding the 'Hide Tabs' and reactivating the menus. If you make that a 'hidden' feature meaning that the user has to enter this one manually in the json from a computer then it would make it secure. I don't understand why it's ugly to be able to hide the option?

**Comment by HamletDuFromage** [comment]
What I mean by ugly is that it that the existing tools_tab.cpp is already kind of gross. and I'd like to not have to parse a json, verify keys exist and scope stuff inside if statements for a feature that will be hidden https://github.com/HamletDuFromage/aio-switch-updater/blob/master/source/tools_tab.cpp

I I did make it possible to hide tools though, I should publish the update very soon

**Comment by pixeltester** [comment]
Hiding the entire Tools tab is not a good solution because there's a lot of useful or even essential options in there. The main request was to hide the 'Hide Tabs' tool but I think I confused matters by asking to hide other tools individually.

Hopefully you'll reconsider that. Sorry to sound negative but I'm just trying to give you good feedback. I appreciate you considering this issue!

**Comment by HamletDuFromage** [comment]
see https://github.com/HamletDuFromage/aio-switch-updater/issues/113
