### ISSUE TITLE
Request - Update SigPatches with Atmosphere

### ISSUE THREAD

**Issue by bachato** [HamletDuFromage/aio-switch-updater#54]
When updating Atmosphere, could you add an option, maybe with a checkbox to activate and deactivate, that would also download the SigPatches that match the current version of atmosphere being updated, if they are available?

**Comment by HamletDuFromage** [comment]
I don't actually hardcode any url, ams, sigpatches or otherwise, so there would be no way to know which sigpatches the user needs. You can just download the sigpatches before installing ams (or after) and be fine

**Comment by bachato** [comment]
ok thanks
