### ISSUE TITLE
Mariko support

### ISSUE THREAD

**Issue by BlackRabbit22** [HamletDuFromage/aio-switch-updater#55]
As you've stated, on Mariko one cannot launch payloads from hos, however if the console reboots, it reboots into a payload. 

You could create a payload that renames the `payload.bin` file to `payload.bin.tmp` and then have the payload that handles updating be named to `payload.bin`. Cause the switch to reboot, and it will reboot into the payload that handles updating, once its done with its operations, rename `payload.bin.tmp` to `payload.bin` and force a reboot again.

**Comment by HamletDuFromage** [comment]
yeah, mariko support is something I'm thinking a out (last commit shows I'm now detecting it), but the problem is that I believe payloads have to be written to support mariko, and I don't know the first thing about writting payloads :^)
But maybe once I read up on it more

**Comment by BlackRabbit22** [comment]
Yeah I understand, just a suggestion. I don't know much about writing payloads either, otherwise I would've submitted a PR instead of making a suggestion :)

Still, thank you for your work.

**Comment by rashevskyv** [comment]
You can use tegraExplorer and it's built in script language. Works fine on mariko

**Comment by HamletDuFromage** [comment]
> You can use tegraExplorer and it's built in script language. Works fine on mariko

There isn't even a need for that, I can just modify the payload to do what BlackRabbit mentioned, I just haven't got around to do it tbh

**Comment by HamletDuFromage** [comment]
tell you what @rashevskyv , if you're willing to help me test it, I'll try to do it in the next few days

**Comment by rashevskyv** [comment]
> 
> 
> tell you what @rashevskyv , if you're willing to help me test it, I'll try to do it in the next few days

Sure. Just working on it for my AIO package

**Comment by HamletDuFromage** [comment]
Well if you're doing it, then there's no point in me doing it at the same time. Let me know !

**Comment by rashevskyv** [comment]
Sure. I will ping you when I am done

**Comment by rashevskyv** [comment]
Script that I will be use for my package 
[startup.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6517923/startup.zip)

**Comment by HamletDuFromage** [comment]
@rashevskyv I looked at it and I'm sure it works but it seems hard to maintain. I tried to do it but I can't test it since I only have a v1 switch. Do you think you could test it for me? I pushed the changes to my repo and here is the app compiled
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6523828/aio-switch-updater.zip)

**Comment by rashevskyv** [comment]
My modchip going mad after reboot. 
Payload size that app copied to SD is different than TegraExplorer

![изображение](https://user-images.githubusercontent.com/18294541/119169365-9429d000-ba6a-11eb-82b0-3cd8699f783e.png)

**Comment by rashevskyv** [comment]
Ah, you are still using your own payload. 
I have used TegraExplorer for mariko update and all works like a charm

**Comment by HamletDuFromage** [comment]
Well, I don't use TegraExplorer, I use my own payload.
https://github.com/HamletDuFromage/aiosu-rcm/blob/71b9c33fcb75754712941599837bbcddbd4525e4/bootloader/main.c#L438

It should also create payload.aio which is either ams or hekate, depending on what exists on your sd card
https://github.com/HamletDuFromage/aio-switch-updater/blob/master/source/dialogue_page.cpp#L29

I hope your modchip is ok. Maybe my payload isn't fully compatible with Mariko switches

**Comment by rashevskyv** [comment]
Modchip is fine, thanks :) 
I think your payload cannot work with mariko

**Comment by rashevskyv** [comment]
https://github.com/rashevskyv/kefir-updater

I forked aio-switch-updater and add tegraexplorer instead of aio-rcm (and removed all functions that i do not need in my aio-pack). I am not a programmer at all and my methods are far from elegant, but all what I need is works.

**Comment by HamletDuFromage** [comment]
I saw it, and if it works then it's great. However I would prefer to not rely on tegraexplorer and scripts to make everything easier to manage. I'll try to update my payload and maybe I can ask you to test it for me again?

**Comment by HamletDuFromage** [comment]
Added in 2.5.0
https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.5.0
