### ISSUE TITLE
Cheat updater Cheatslip 

### ISSUE THREAD

**Issue by Shadowrritter** [HamletDuFromage/aio-switch-updater#56]
When multible or all Cheats are choosen in the Cheat updater via Cheatslip it merches the first 3-4 ( just tested with 2 games)  together and ignores the rest.

**Comment by HamletDuFromage** [comment]
I tried and successfully downloaded 14 cheatsheets totaling 1200 LOCs for animal crossing, so I can't replicate.. What game(s) did you try?
