### ISSUE TITLE
Application won't open under certain network conditions

### ISSUE THREAD

**Issue by FlyingBananaTree** [HamletDuFromage/aio-switch-updater#57]
I sometimes use my Switch on a local area network without internet and the application won't open with the following setup, obviously no internet prevents many features being used but still there are some useful tools in your app that can't be accessed. I realize this is a somewhat niche use case but it might improve network checks in general if fixed.

It sounds like it's related to https://github.com/HamletDuFromage/aio-switch-updater/issues/51 although you say that's fixed.

To reproduce:
1. Use nifm-ctest patches so local area network can still work without internet https://github.com/misson20000/exefs_patches#nifm-ctest
2. connect to your local area network that doesn't have internet access
3. black screen Nintendo style error occurs the first time or just a black screen on subsequent attempts

**Comment by HamletDuFromage** [comment]
I'll try to look into it, problem is that I don't have access to my router right now. The network check are quite simple: they don't exist :^)

**Comment by HamletDuFromage** [comment]
If you have the edizon applet or anyway to look at your local IP address, could you let me know what it is when connected to a local area network?

**Comment by FlyingBananaTree** [comment]
> 
> 
> If you have the edizon applet or anyway to look at your local IP address, could you let me know what it is when connected to a local area network?

192,168.x.x

**Comment by FlyingBananaTree** [comment]
> 
> 
> If you have the edizon applet or anyway to look at your local IP address, could you let me know what it is when connected to a local area network?

192.168.x.x

**Comment by HamletDuFromage** [comment]
Yeah as expected, can't use that then

**Comment by HamletDuFromage** [comment]
Could you try singleling out specific tabs with the hide tabs option in tools? Hide everything, and if it works add one tab at a time to see if there is a culprit

**Comment by FlyingBananaTree** [comment]
It seems like it's anything apart from the About tab. I did notice that undocking can 'unlock' the application from the black screen so obviously it's stuck at trying to access the internet which it believes it has access to. Perhaps this is just a side effect of setting things up like this and not possible to workaround on the homebrew side.

**Comment by HamletDuFromage** [comment]
Sure, but having the about page loading means that it tried fetching the latest release tag and that it (successfully) failed. So it's more than stuck at trying to access the internet, it must be specific functions. Could you hide all the tabs and go to tools->download payloads see if it hangs there? Thank you for checking it out btw

**Comment by FlyingBananaTree** [comment]
No problem. Yes it hangs in the same fashion there.

**Comment by HamletDuFromage** [comment]
I'm not really able to reproduce the condition, so I won't be able to fix it for the foreseeable future
