### ISSUE TITLE
Opening the application takes forever

### ISSUE THREAD

**Issue by ali-ee** [HamletDuFromage/aio-switch-updater#58]
Hello @HamletDuFromage ,

Wherever I open the app from, forwarder or h menu, it takes forever to load.

Is this intentional?

**Comment by HamletDuFromage** [comment]
It's only as slow as your internet connection. I have 15Mb/s down it takes less than 2 seconds to launch. If you try loading it in airplane mode, it should instant

There's not really much I can do about that

**Comment by ali-ee** [comment]
If the only limiter is internet connection than it's really interesting. Because I have a 100 Mbit connection.
Is there anything that comes to mind that I can try?

**Comment by HamletDuFromage** [comment]
1 minute is definitely forever and not normal behavior. The only website I connect to is github. Could you try pinging those and tell me if the time if outrageous?
```
ping api.github.com
ping raw.githubusercontent.com
```
Also maybe try this nro. I changed the way to retrieve the latest release for the update check. I'm doubtful this will help, but maybe it will
[aio-switch-updater.nro.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6051571/aio-switch-updater.nro.zip)

**Comment by ali-ee** [comment]
Average ping for both is  around 51ms from my PC which is located 2 rooms away from my living room where router is located.
Switch is in the same room with my router.
tried your new nro: didn't help
Airplane mode didn't make a difference.

**Comment by ali-ee** [comment]
After writing to you my Atmosphere version, I realized that I was very far behind and decided to update :)

After updating, app now opens very quickly.

Sorry for taking your time and thanks a lot for this great application.

**Comment by HamletDuFromage** [comment]
Still odd that it doesn't work with an old ams, but I'm glad it does work at all :)
