### ISSUE TITLE
Downloading Cheat sheets from cheatslips.com

### ISSUE THREAD

**Issue by SaifKamil** [HamletDuFromage/aio-switch-updater#59]
Hi,
How do i go about in downloading the cheat sheets from cheatslips.com by using AIO Switch Updater?

**Comment by HamletDuFromage** [comment]
create an account on cheatslips and enter your login info when prompted. If they keyboard to enter your login info doesn't show when clicking "download cheatslips.com cheat sheets', make sure you're launching the app with full ram access, via title redirection.
Then pick a game, select cheetsheet(s), press B and they'll be downloaded

![](https://www.cheatslips.com/homebrews/static/img/aio-switch-updater/download.jpg)

**Comment by SaifKamil** [comment]
![1614455852430138871374530994618](https://user-images.githubusercontent.com/79765438/109398651-1e392f80-7979-11eb-8820-803fc463ceb2.jpg)
What does this mean?

**Comment by HamletDuFromage** [comment]
launch hbmenu by holding R while launching a game

**Comment by SaifKamil** [comment]
It worked! Thank you for the assistance!
