### ISSUE TITLE
[Feature request].  Disable all external sysmodules

### ISSUE THREAD

**Issue by fennectech** [HamletDuFromage/aio-switch-updater#60]
I would like to see a dialog that disables all external sysmodules on update.  (Delete all non atmosphere boot2.flags

**Comment by HamletDuFromage** [comment]
I already have a dialogue that deletes the contents folder, although you're right that deleting boot2.flag is a better way to do things. I'll add it

**Comment by fennectech** [comment]
Wiping out contents is a no go for litteraly anyone who uses mods.

**Comment by HamletDuFromage** [comment]
Yeah, i do warn about it though. This was just a quick hack because of people who update with sysmodules on

**Comment by fennectech** [comment]
You might be able to wipe out non atmosphere sysmodules too.    By checking the contents folders against the installed/archived titles & atmosphere contents

**Comment by HamletDuFromage** [comment]
Deleting boot2.flag is enough so that it boots even it's broken right?

**Comment by fennectech** [comment]
Yup.  Removing boot2.flag will stop the sysmodule from launching

**Comment by HamletDuFromage** [comment]
done in 2.4.0

**Comment by fennectech** [comment]
TITS

**Comment by squee666** [comment]
> Deleting boot2.flag is enough so that it boots even it's broken right?

better idea

renaname boot2.flag to boot2.bak

add option in the AIO to re-enable all sysmodules

your current solution to use OVL menu doesnt work if it gets disabled when using tool
and manually searching contents which can contain a mass amount of folders just to manaully create new boot2.flag files is impractical and defeats using your AIO in the first place

**Comment by HamletDuFromage** [comment]
> > Deleting boot2.flag is enough so that it boots even it's broken right?
> 
> better idea
> 
> renaname boot2.flag to boot2.bak
> 
> add option in the AIO to re-enable all sysmodules
> 
> your current solution to use OVL menu doesnt work if it gets disabled when using tool
> and manually searching contents which can contain a mass amount of folders just to manaully create new boot2.flag files is impractical and defeats using your AIO in the first place

boot2.flag is an empty file, there really is no point in creating a backup and cluttering the SD card further. You may use DeepSea toolbox (or Hekate toolbox which is the same app I believe) to create flags for sysmodules that don't have it. Creating a backup doesn't really solve the problem you're describing anyways

**Comment by fennectech** [comment]
tesla and sysmodules-ovl is a good way to manage sysmodule s
