### ISSUE TITLE
Downloading codes from cheatslip On the all in one Nintendo switch updater problem

### ISSUE THREAD

**Issue by bobby668** [HamletDuFromage/aio-switch-updater#63]
everytime i try to download cheats from cheatslip using the All in one Nintendo switch updater by pressing B

nothing happens at all

i do not get my cheats at all

**Comment by HamletDuFromage** [comment]
Do you select them by clicking a on the cheatsheets you want, and then press B? There isn't any indication of it having worked, so if it doesn't say anything, it should be good.

Then if you go your game, you should see them with the Edison tesla overlay

**Comment by bobby668** [comment]
I do not think i have edison tesla overlay module installed

how do i install the Edison tesla overlay Module

**Comment by HamletDuFromage** [comment]
https://www.cfwaifu.com/edizon-cheats/
This guide covers the whole thing pretty well

**Comment by bobby668** [comment]
is there anyway to make cheats work without using the edison tesla overlay at all

after you are done downloading them on the All in one nintendo switch updater

**Comment by bobby668** [comment]
I do not want to break my modded nintendo switch with overlays i know nothing about

**Comment by bobby668** [comment]
The 3ds cheat overlay broke many things on it in the past

and i do not want it to break my switch next as well

**Comment by HamletDuFromage** [comment]
No the overlay allows you to enable them. You wouldn't be breaking anything by using it. You should read up more on how to use cheats with the switch, I think you're confused.

My homebrew simply downloads cheat files. It is recommended to use Edison to activate them.
