### ISSUE TITLE
Request / suggestion - language select

### ISSUE THREAD

**Issue by spacerat1** [HamletDuFromage/aio-switch-updater#65]
Hi, although i live in germany and there is a german translation for aio available, i prefer the english translation. Could you make an option, either in app or as a .json file, where i can choose the prefered language. Thanks in advance.

**Comment by HamletDuFromage** [comment]
Added in v2.4.2 :) https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.4.2

**Comment by spacerat1** [comment]
Wow, that was fast. Many thanks. :)Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: HamletDuFromage ***@***.***> Datum: 14.03.21  16:30  (GMT+01:00) An: HamletDuFromage/aio-switch-updater ***@***.***> Cc: Andre Koseda ***@***.***>, Author ***@***.***> Betreff: Re: [HamletDuFromage/aio-switch-updater] Request / suggestion - language select (#65) 
Added in v2.4.2 :) https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.4.2
