### ISSUE TITLE
Joycon color profile support for the Switch lite

### ISSUE THREAD

**Issue by BlackRabbit22** [HamletDuFromage/aio-switch-updater#66]
It would be nice if Switch lite users could change the color of their device as well.

**Comment by xiaojiangGangGang** [comment]
It would be nice if Switch lite users could change the color of their device as well.

**Comment by HamletDuFromage** [comment]
Color variation for the switch lite is stored in prodinfo https://switchbrew.org/wiki/Calibration and afaik is undocumented
It would be possible to modify it, but I don't want to fuck with prodinfo as any mistake would result in corruption

**Comment by HamletDuFromage** [comment]
@xiaojiangGangGang @BlackRabbit22 I actually might do it, it seems easy enough but I'd need the help of someone owning a switch lite to help me, as I don't have one. Do either of you have one?

**Comment by JonJaded** [comment]
Hey there Ham. I used your change Joy-Con color tool and it seems to not work (for actual joycons) I see the default "Animal Crossing New Horizons" option, but after generating a json from the site listed, the configuration does not show up. Backing up also leads to a crash.

**Comment by HamletDuFromage** [comment]
@JonJaded Please open a separate issue and link the file you generated + the crash report
