### ISSUE TITLE
[Localization updated] Traditional Chinese langs for 2.4.2

### ISSUE THREAD

**Issue by qazrfv1234** [HamletDuFromage/aio-switch-updater#67]
Hello,
the attachment for aio-switch-updater v2.4.2 (the latest menus.json )

[zh-rTW_v2.42.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6163914/zh-rTW_v2.42.zip)

Many thanks,
Leo

**Comment by HamletDuFromage** [comment]
Thanks a bunch, added in 2.4.3 :)
