### ISSUE TITLE
Cheat codes do not load

### ISSUE THREAD

**Issue by jokesonyou123** [HamletDuFromage/aio-switch-updater#68]
After downloading gbatemp.net (38120) codes, not able to select any cheats codes from 'view installed cheats' menu. Games are listed but nothing opens up from there. On current FW and using Atmosphere. Any assistance would be greatly appreciated.

**Comment by HamletDuFromage** [comment]
Follow this guide. The app only download cheatsheets https://www.cfwaifu.com/edizon-cheats/
