### ISSUE TITLE
[Localization] Polish localisation

### ISSUE THREAD

**Issue by teddy74eva** [HamletDuFromage/aio-switch-updater#69]
[2.4.2_pl-PL.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6172470/2.4.2.pl-PL.zip)

Hi,
As a thank you for your amazing app, I've decided to provide localization files for Polish language. They should be attached as a zip file. They're based on the latest en-US files. Please do hit me up if there's any issue in them and I'll fix them as soon as possible.

Best regards,
Tobiasz

**Comment by HamletDuFromage** [comment]
Thanks a bunch, added in 2.4.3 :)
The switch doesn't offer polish language natively, so you have to manually toggle it in the app, but it seems to be all good.
