### ISSUE TITLE
Failed to build aio-switch-updater

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#72]
![image](https://user-images.githubusercontent.com/64573431/112956857-74191700-9173-11eb-8454-4bd3852e2be5.png)

I stuck on this step when building aio-switch-updater. I have tried to replace the (nproc) into the local file direction(C:/devkitPro/msys2/usr/bin/nproc.exe) but still failed

I am sorry about my poor English

**Comment by HamletDuFromage** [comment]
nproc might be Linux only. Do `make` or `make -j4` if you have for processor cores

**Comment by carcaschoi** [comment]
thx for your reply, let me have a try. If I succeed, I will close the issue

**Comment by carcaschoi** [comment]
![2021-03-30 (1)](https://user-images.githubusercontent.com/64573431/112992352-adb14880-919a-11eb-9f59-549ca942ab14.png)
![2021-03-30 (2)](https://user-images.githubusercontent.com/64573431/112992363-b013a280-919a-11eb-9bec-1ba7df0983ae.png)
![2021-03-30 (3)](https://user-images.githubusercontent.com/64573431/112992372-b1dd6600-919a-11eb-86a7-a8157be4ffa6.png)

**Comment by carcaschoi** [comment]
failed again. And I am sorry if I bother you

**Comment by HamletDuFromage** [comment]
No don't worry, you're fine! Looks like you're missing libraries, GLFW in particular. You need to install those libraries 

```switch-glfw
switch-curl
switch-glm
switch-zlib```
https://github.com/HamletDuFromage/aio-switch-updater#build

**Comment by carcaschoi** [comment]
![2021-03-30 (4)](https://user-images.githubusercontent.com/64573431/112996455-c3c10800-919e-11eb-82c4-a7b548d434e2.png)

finally......

HamletDuFromage, Thank you for your teaching. This is a nice experience.

**Comment by HamletDuFromage** [comment]
I'm glad it worked!

**Comment by carcaschoi** [comment]
I have a New error. I change The new icon file which is the same format (jpg) and 256 x256 . But it cause a building error. When I change back the original jpg file. It can be built again. How can I fix it if I want to use a new icon?

here is the photo
![image](https://user-images.githubusercontent.com/64573431/113256976-87a3b980-92fc-11eb-809b-b60c2c90f8c0.png)

here is the new icon jpg file I made
![icon](https://user-images.githubusercontent.com/64573431/113257097-ad30c300-92fc-11eb-9bb2-89d161cf082e.jpg)

**Comment by HamletDuFromage** [comment]
I can't really look right now, but try to do `make clean` and then build it again with `make`

**Comment by carcaschoi** [comment]
![image](https://user-images.githubusercontent.com/64573431/113281659-77013c80-9318-11eb-8e43-e538b8f04d3f.png)

I have been fresh clone the switch-aio-updater repository. Then I test it again. It show the error again

**Comment by HamletDuFromage** [comment]
Try with another icon, line this one for instance
https://www.github.com/HamletDuFromage/switch-cheats-updater/tree/master/icon.jpg

There is probably something wrong with your jpeg. How did you make it?

**Comment by carcaschoi** [comment]
Let me test it. Thx for your advice

**Comment by carcaschoi** [comment]
![image](https://user-images.githubusercontent.com/64573431/113285034-0ad50780-931d-11eb-99f1-85519932df52.png)

It is very strange. I use the cheat-updater icon and test it. Ii still have error. When I change back the original switch-aio-updater icon. The problem slove. Do you have any idea

**Comment by HamletDuFromage** [comment]
![image](https://user-images.githubusercontent.com/61667930/113320842-44a11080-9313-11eb-8dc4-61b0403bfb76.png)

![2021040117540600-C69CBEDD2A82ABF5988F293C4CA42C5D](https://user-images.githubusercontent.com/61667930/113320728-20453400-9313-11eb-9a94-2b56edd3d983.jpg)
It worked for me, I don't know what it is. Maybe so weird windows specific thing, or the Chinese locale messing things up? Either way I'm afraid I can't really help you..

**Comment by carcaschoi** [comment]
It doesn't matter. I would try another method. Thx for your help🙇‍♂️🙇‍♂️
