### ISSUE TITLE
Download cheats

### ISSUE THREAD

**Issue by merhovon** [HamletDuFromage/aio-switch-updater#76]
I have the version 2.4.4 and as soon as I want to download the cheats the SXOS 3.1 crashes and I have to restart the switch.
I get error code: 2349-0008 displayed.

**Comment by HamletDuFromage** [comment]
could you try with 2.4.7 and tell me if the issue persists? It's hard for me to debug for SXOS

**Comment by merhovon** [comment]
Unfortunately I get the same error message with the version.

**Comment by HamletDuFromage** [comment]
Does it still not work?
