### ISSUE TITLE
broken in 12.0 and atmosphere 0.19

### ISSUE THREAD

**Issue by fmg3656** [HamletDuFromage/aio-switch-updater#77]
crashes.  instantly

**Comment by hax4dazy** [comment]
Yeah I can back this up. Tried it with applet mode and with full ram mode and it still crashes.

**Comment by Stelrick** [comment]
![20210411_134211_HDR](https://user-images.githubusercontent.com/71048316/114315267-3352c380-9acc-11eb-90f8-2c1daa1b3e5f.jpg)

If it helps, that should be a picture of the crash screen

**Comment by HamletDuFromage** [comment]
recompiling with libnx master as we speak

**Comment by HamletDuFromage** [comment]
it'll take a lil bit more than expected, need to update borealis for hid changes

**Comment by HamletDuFromage** [comment]
Latest version supports AMS 0.19. I'll fix it better soon

**Comment by fmg3656** [comment]
I updated to the latest version, it still won't open when I upgraded to 0.19 and fw12.
