### ISSUE TITLE
build 2.4.6 cannot be used from the forwarder

### ISSUE THREAD

**Issue by fmg3656** [HamletDuFromage/aio-switch-updater#78]
updated to 2.4.6 then updated to atmosphere 0.19 and fw12.  forwarder no longer functions.   works from atmosphere menu.

**Comment by HamletDuFromage** [comment]
Forwarders are broken in 0.19, not much I can do but make a new one once it's fixed

**Comment by fmg3656** [comment]
gotcha.   thanks for all the hard work!
