### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by sardelisp** [HamletDuFromage/aio-switch-updater#79]
After updating to version 2.4.6 app crashes on opening. I am on atmos 0.18.1 and hos 11.0.1

**Comment by HamletDuFromage** [comment]
Do you know if it was it crashing in 2.4.5?

**Comment by sardelisp** [comment]
I confirm that I had 2.4.5 working like a charm before update to latest

**Comment by HamletDuFromage** [comment]
Ah, i know exactly what it is then. Thank you, will try to fix it fast

**Comment by HamletDuFromage** [comment]
Also do you mind if I send you a nro to test it? I don't have access to my switch rn

**Comment by sardelisp** [comment]
Of course man! psarbel@hotmail.com

**Comment by HamletDuFromage** [comment]
[aio-switch-updater.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6299314/aio-switch-updater.zip)

Let me know! It should be ok I think

**Comment by sardelisp** [comment]
"the software was closed because an error occurred"
 Same issue🙄

**Comment by HamletDuFromage** [comment]
I'll have to get ams 18 and try for myself then, sorry for the inconvenience, I'll try to do it today

**Comment by sardelisp** [comment]
Yes I think the problem is to do the app working in atmos 0.18.1 and at the same time in 0.19.
Don't be sorry, we must be thankful to you anyway my friend.!!

**Comment by Dantasstic** [comment]
I have this same issue, running AMS 0.18.1 on FW 11.0.1

I have reverted to 2.4.4 version of the app as well and following this for the fix :)

**Comment by HamletDuFromage** [comment]
Fixed in 2.4.7
