### ISSUE TITLE
Failed to update atmosphere

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#80]
aio-switch-updater version: v2.4.6
I want to update atmosphere from 0.19.0 to 0.19.1, Then I choose 
1. [Update Atmosphere]
2. Choose The First Option (atmosphere-0.19.1-master-997e4dd6+hbl-2.4.1+hbmenu-3.4.0.zip)
3. choose [yes] for all the option
4. After reboot the console, it still show 12.0.0|AMS M.19.0|E but not 12.0.0|AMS M.19.1|E

**Comment by HamletDuFromage** [comment]
Stratosphere.romfs seems to be read-only, I'll fix it

**Comment by HamletDuFromage** [comment]
Should be better now, please try with 2.4.7

**Comment by carcaschoi** [comment]
thx
