### ISSUE TITLE
Question about glfw

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#81]
I dont have so many experience. I install switch-glfw with msys2 before. What do I need to do to install your switch-glfw [folk]. Thx

**Comment by HamletDuFromage** [comment]
I used this a basis of how to compile it 
https://github.com/devkitPro/pacman-packages/blob/master/switch/glfw/PKGBUILD

**Comment by carcaschoi** [comment]
Let me have a try😀，thx

**Comment by carcaschoi** [comment]
![2021-04-14 (1)](https://user-images.githubusercontent.com/64573431/114700062-a15cec00-9d53-11eb-80ca-e71b88cad803.png)

**Comment by HamletDuFromage** [comment]
There is no patch here, you should read PKGBUILD and understand what it is doing

```
source /opt/devkitpro/switchvars.sh 

cmake -G"Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/switch.cmake \ -DCMAKE_INSTALL_PREFIX=$PORTLIBS_PREFIX \ -DCMAKE_C_FLAGS="$CFLAGS $CPPFLAGS" \ -DCMAKE_AR="/opt/devkitpro/devkitA64/bin/aarch64-none-elf-gcc-ar" \ -DGLFW_BUILD_EXAMPLES:BOOL=OFF -DGLFW_BUILD_TESTS:BOOL=OFF -DGLFW_BUILD_DOCS:BOOL=OFF \ -DGLFW_VULKAN_STATIC:BOOL=ON -DGLFW_EGL_STATIC:BOOL=ON \ . 

make
```
This is the part you should use. Also you may need to add `set(SWITCH_LIBNX ON)` to your CMakeList

**Comment by carcaschoi** [comment]
thx for your teaching🙏
