### ISSUE TITLE
Bug (aio-switch-updater)

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#82]
previous version of atmosphere & aio-switch-updater also have this bug
here is the video:
https://youtube.com/shorts/FcM3pX0sS-U?feature=share

If I press A when the list of download doesn't show, it will have error

**Comment by HamletDuFromage** [comment]
Indeed, happens on latest AMS too. Could you tell me if it happens with aio-switch-updater 2.4.4? I can't test these right now

Thanks for letting me know

**Comment by carcaschoi** [comment]
ys, this error seems have been contained for a long tome

**Comment by carcaschoi** [comment]
I think it is the problem of menu of aio-switch-updater

**Comment by carcaschoi** [comment]
「Update CFW」also have this error

**Comment by HamletDuFromage** [comment]
sorry to bother you again, but could you try with this version?
https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.2.1

This might be caused by a change I made to Borealis

**Comment by carcaschoi** [comment]
> sorry to bother you again, but could you try with this version?
> https://github.com/HamletDuFromage/aio-switch-updater/releases/tag/2.2.1
> 
> This might be caused by a change I made to Borealis

Let me downgrade switch and have a test

**Comment by HamletDuFromage** [comment]
if it's too annoying for you, I'll do it, don't worry

**Comment by carcaschoi** [comment]
I am testing now.😀

**Comment by carcaschoi** [comment]
v2.2.1:
After pressing A, no any response later until I press home button
https://youtu.be/tYl_J4U8_54

**Comment by HamletDuFromage** [comment]
Alright, seems like a borealis issue then, I'll work on it. Thank you for bringing that to my attention

**Comment by carcaschoi** [comment]
「About」does not have error, may be you can put the 「about」 modules to other tab when ns is in airplane mode(or does not connect wifi)

**Comment by HamletDuFromage** [comment]
Fixed, thank you
