### ISSUE TITLE
Request : option to replace the default reboot_payload.bin by the latest hekate

### ISSUE THREAD

**Issue by LeMageFro** [HamletDuFromage/aio-switch-updater#85]
First of all thank you very much for this amazing tool, it's incredibly convenient.

I don't know if we're many users in this case, but when I update my setup through AIO switch updater, there is just one tiny step that I still need to do manually : replacing the default atmosphere/reboot_payload.bin (which is just a renamed copy of fusee-primary.bin from my understanding) by the latest hekate properly renamed. This way when the console restarts after a crash, when I restart it manually through the power button, or when I use the "reboot to payload" homebrew, the console automatically reboots to hekate rather than to fusee-primary, which have the inconvenient of always prioritizing emuMMC.
So having the option to do that automatically through the homebrew would just be the icing on the cake.

I assume that should be a simple addition, but if you have better things to do or deem that too few people care I completely understand.

Thanks in advance !

**Comment by HamletDuFromage** [comment]
There are currently 2 ways to do it. You can go to the "inject payload" menu in Tools and set any payload to reboot_payload

Or you download this file https://github.com/HamletDuFromage/aio-switch-updater/blob/master/copy_files.json and place it in your config/aio-switch-updater directory. You can then select the "batch copy" menu in Tools to perform the copy you want. If you have the json file in the proper directory, the copy will also take place after every update. Feel free to edit the file to do the operations you want

**Comment by LeMageFro** [comment]
That's awesome, thank you for the quick answer !
