### ISSUE TITLE
Updating Deep Sea Rebooting To Special Payload

### ISSUE THREAD

**Issue by sawyermade** [HamletDuFromage/aio-switch-updater#86]
When "rebooting to special payload" it just loads back to hekate and when I try to run emummc with cfg from hekate, I get black screen and have to reboot, then mount SD card, copy deep sea manually, and run in order to get it to work. Not sure what normal behavior is?

**Comment by HamletDuFromage** [comment]
It shouldn't be happening, you probably had some files from a previous install that were conflicting with the new CFW version you're installing. 
In this case, updating manually (by deleting existing files) is the best course of action.

**Comment by sawyermade** [comment]
Okay but after I did that, I tried to re-run it in order to be able to test running it again and it did the same thing. What is expected behavior, like what does the special payload look like?

**Comment by sawyermade** [comment]
I removed everything and put everything back manually and tried again and seemed to work. Guess I will know for sure with next atmosphere update, thanks for the response.
