### ISSUE TITLE
Question: How to re-enable sysmodules after firmware update?

### ISSUE THREAD

**Issue by Enzemo** [HamletDuFromage/aio-switch-updater#87]
Hi, updated my firmware and was prompted to disable sysmodules, which I accepted, but now I can't work out how to re-enable them. All my files seem to be in the right place and the config doesn't seem changed so I can't work out how they've been disabled to turn them back on.

Thanks

**Comment by HamletDuFromage** [comment]
Use this https://github.com/WerWolv/ovl-sysmodules 
Or this https://github.com/Team-Neptune/DeepSea-Updater
Or manually create empty boot2.flag files in the corresponding directories in atmosphere/contents

**Comment by Enzemo** [comment]
I already have https://github.com/WerWolv/ovl-sysmodules but the OVLmenu is disabled too, so the button combo wouldn't bring it up. Deepsea seems to have fixed it though, cheers mate
