### ISSUE TITLE
Missing Update Sigpatches

### ISSUE THREAD

**Issue by digpub** [HamletDuFromage/aio-switch-updater#89]
Hi, I have just installed AIO (latest version) and the Update Sigpatches option is missing. Any suggestions would be appreciated.
Regards

**Comment by HamletDuFromage** [comment]
They're hidden when you download them from the hbappstore to comply with their rules. You can unhide them in tools->hide tabs

**Comment by digpub** [comment]
Thanks missed that.
Regards
