### ISSUE TITLE
[Bug] Corrupted filesystem / stratosphere.romfs issue after update

### ISSUE THREAD

**Issue by 424778940z** [HamletDuFromage/aio-switch-updater#93]
## ENV Info
```
System: emuEMMC 10.2.0
Before update running: Atmosphère 0.18.0
Updating to: Atmosphère 0.19.3
SD: EXFAT Samsung 512G (not a fake card, tested by write 100% then read back when I got it)
```

## What I did
1. Did chkdsk on computer before update, no issue found.
2. Downloaded and installed latest AIO from GitHub to sdcard.
3. Boot into system normally, opened AIO, started update.
4. Chose `atmosphere-0.19.3-master-691a453d+hbl-2.4.1+hbmenu-3.4.0.zip` option
5. Chose keep all configure files.
6. Auto reboot

Then I got following error message.
```
A fatal error occurred when running Atmosphére.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
```

## Troubleshoot
Tried remove all configure files, didn't help.
Tried archive bits fix, didn't help.
Did some research found following from Atmosphère 0.19.0 change log
`Atmosphère's system modules are now bundled together in the single file "stratosphere.romfs".`
And noticed I do not have `stratosphere.romfs` in the folder but have `stratosphere.romfs.aio` instead.
Did chkdsk just in case, then found the filesystem is corrupted, and bit map for `stratosphere.romfs.aio` has been damaged.

## Fix
Since chkdsk fixed filesystem.
I simply delete `stratosphere.romfs.aio` then get a copy of `stratosphere.romfs` from `atmosphere-0.19.3-master-691a453d+hbl-2.4.1+hbmenu-3.4.0.zip` put in same folder

## My Guess
I'm a embedded system developer but has no experience on NS.
My guess is AIO may need to do a filesystem sync (wait for it done) then also put a small delay before restart or jump to payload.
Large sdcads may have internal controller with cache not flashed, then jump to payload may reset it before those buffer can be flushed?

**Comment by HamletDuFromage** [comment]
First of all, I'm glad you were able to fix your issue without real corruption. The exFAT driver is notoriously bad on the Switch, and I do have a disclaimer saying you shouldn't use it.
https://github.com/HamletDuFromage/aio-switch-updater/blob/6c13a2f81703b0f12a76841e56cf3c51fe23a4b0/source/extract.cpp#L60
As you can see here, we close the descriptor for `stratopshere.romfs.aio` when leaving the scope, so we shouldn't be writing to that file when shutting down. If what you say is right, and I need to add a delay, then this could be added. This is already the case after you download Hekate, but not when rebooting to RCM directly after getting AMS.

**Comment by HamletDuFromage** [comment]
Wait, also do you think calling [`sync()`](https://en.cppreference.com/w/cpp/io/basic_istream/sync) is needed?

**Comment by 424778940z** [comment]
I would suggest do a `sync()` before reboot, not really sure how exFAT driver works on Switch, but I think a manual sync is worth trying.

**Comment by HamletDuFromage** [comment]
fair enough, surely can't hurt

**Comment by HamletDuFromage** [comment]
So `sync()` doesn't exist on the switch, and apparently there isn't much you can do to prevent corruption when using homebrew, something about corruption of the FAT table caused by concurrent accesses. The better solution would be to switch to fat32

**Comment by 424778940z** [comment]
Hum.., that's odd.
Closing this issue then.

**Comment by HamletDuFromage** [comment]
@424778940z Latest update should make it so corruption happens less (or not at all) after injecting a payload
