### ISSUE TITLE
I made a nsp forwarder for All in one switch updater which support ams 0.19

### ISSUE THREAD

**Issue by carcaschoi** [HamletDuFromage/aio-switch-updater#98]
[All-in-One Switch Updater_05000AA286374000.zip](https://github.com/HamletDuFromage/aio-switch-updater/files/6568580/All-in-One.Switch.Updater_05000AA286374000.zip)

Youtube testing video: https://youtu.be/qRJlYsYc9Yc

**Comment by HamletDuFromage** [comment]
Thank you, but I don't think I'll include it. Some users have reported crashes when the user forwarders that do not happen when using title redirection

**Comment by carcaschoi** [comment]
oic
